import type { Translations } from '../types';

// Simplified Chinese (zh) locale for Vault Operator.
// Mirrors src/i18n/locales/en.ts key-for-key. Brand names, model IDs and URLs
// stay in English on purpose. {{var}} placeholders are preserved verbatim.
export const zh: Translations = {
    // =========================================================================
    // Settings — Tab Groups
    // =========================================================================
    'settings.group.providers': '服务提供商',
    'settings.group.agentBehaviour': '智能体',
    'settings.group.customize': '自定义',
    'settings.group.vault': '知识库',
    'settings.group.advanced': '高级',
    'settings.group.help': '帮助',

    // =========================================================================
    // Settings — Sub-Tab Labels
    // =========================================================================
    'settings.tab.providers': '服务提供商',
    'settings.tab.models': '模型（旧版）',
    'settings.tab.embeddings': '嵌入向量',
    'settings.tab.webSearch': '网页搜索',
    'settings.tab.mcp': 'MCP',
    'settings.tab.connectors': '连接器',
    'settings.tab.vault': '知识库',
    'settings.tab.modes': '智能体',
    'settings.tab.autoApprove': '自动批准',
    'settings.tab.loop': '运行循环',
    'settings.tab.memory': '记忆',
    'settings.tab.rules': '规则',
    'settings.tab.workflows': '工作流',
    'settings.tab.skills': '技能',
    'settings.tab.prompts': '提示词',
    'settings.tab.interface': '界面',
    'settings.tab.shell': '外壳',
    'settings.tab.log': '日志',
    'settings.tab.debug': '调试',
    'settings.tab.backup': '备份',
    'settings.tab.language': '语言',

    // =========================================================================
    // Settings — Models Tab
    // =========================================================================
    'settings.models.introTitle': 'AI 模型',
    'settings.models.introDesc': '配置智能体使用的 AI 模型。可添加多个模型并在它们之间切换。',
    'settings.models.performanceNote': '注意：',
    'settings.models.performanceNoteDesc': '智能体可配合任意模型运行（包括本地模型）。大型前沿模型的效果最佳。',
    'settings.models.headerModel': '模型',
    'settings.models.headerProvider': '提供商',
    'settings.models.headerKey': '密钥',
    'settings.models.headerEnable': '启用',
    'settings.models.headerDefault': '默认',
    'settings.models.empty': '尚未添加模型。点击“+ 添加模型”开始。',
    'settings.models.addModel': '+ 添加模型',
    'settings.models.importFromCode': '从代码导入',
    'settings.models.alreadyExists': '“{{name}}”已存在',
    'settings.models.imported': '已导入 {{count}} 个模型',
    'settings.models.skipped': '已跳过 {{count}} 个（重复）',
    'settings.models.configure': '配置',
    'settings.models.remove': '移除模型',

    // =========================================================================
    // Settings — Embeddings Tab
    // =========================================================================
    'settings.embeddings.introTitle': '按语义搜索',
    'settings.embeddings.introDesc': '让智能体按含义而非精确字词查找笔记。若希望它按主题从知识库中浮现相关笔记，则需要此功能。',
    'settings.embeddings.headingModels': '嵌入模型',
    'settings.embeddings.sectionModelsInfo': '嵌入模型把文本转换为数字（向量）。含义相近的笔记会得到相似的向量，“按语义查找”便以此工作。在此添加一个模型，同一套向量会被语义索引、记忆回想起隐式连接建议复用。',
    'settings.embeddings.headingIndex': '语义索引',
    'settings.embeddings.sectionIndexInfo': '一个本地数据库，为每条笔记（或长笔记的每个分块）存储一个向量。从你的知识库一次性构建，并在你编辑时更新。没有它，按语义搜索就无所匹配。',
    'settings.embeddings.headingConfig': '索引配置',
    'settings.embeddings.sectionConfigInfo': '索引前如何把知识库切成片段、多久重建一次、跳过哪些文件夹。默认值已较为合理；仅当搜索结果系统性地过粗（分块过大）或过噪（分块过小）时再调整。',
    'settings.embeddings.modelsDesc': '嵌入模型为整个知识库的语义搜索提供动力。请恰好选择一个模型作为活动索引。',
    'settings.embeddings.headerModel': '模型',
    'settings.embeddings.headerProvider': '提供商',
    'settings.embeddings.headerKey': '密钥',
    'settings.embeddings.headerActive': '活动',
    'settings.embeddings.empty': '未配置嵌入模型',
    'settings.embeddings.addModel': '+ 添加嵌入模型',
    'settings.embeddings.buildIndex': '构建索引',
    'settings.embeddings.forceRebuild': '强制重建',
    'settings.embeddings.cancel': '取消',
    'settings.embeddings.deleteIndex': '删除索引',
    'settings.embeddings.building': '构建中…',
    'settings.embeddings.rebuilding': '重建中…',
    'settings.embeddings.alreadyExists': '“{{name}}”已存在',
    'settings.embeddings.enableFirst': '请先启用语义索引。',
    'settings.embeddings.alreadyBuilding': '已在构建中…',
    'settings.embeddings.indexBuilt': '索引已构建：{{indexed}}/{{total}} 个文件，跳过 {{errors}} 个。',
    'settings.embeddings.indexRebuilt': '重建：{{indexed}}/{{total}} 个文件，跳过 {{errors}} 个。',
    'settings.embeddings.chunkSizeUpdated': '分块大小已更新。请重建索引以应用新设置。',
    'settings.embeddings.autoIndexEnabled': '已启用变更时自动索引。重新加载 Obsidian 以激活。',
    'settings.embeddings.autoIndexDisabled': '已禁用变更时自动索引。重新加载 Obsidian 以停用。',
    'settings.embeddings.enableIndex': '启用语义索引',
    'settings.embeddings.enableIndexDesc': '让智能体按含义而非仅按关键词查找相关笔记。需要嵌入模型。大型知识库的首次构建可能耗时几分钟。',
    'settings.embeddings.indexPdfs': '索引文档（PDF、办公文档）',
    'settings.embeddings.indexPdfsDesc': '同时索引知识库中的文档文件。文本会被提取并与笔记一起索引。仅跳过无文本可提取的纯图片（扫描）文档。',
    'settings.embeddings.buildIndexName': '构建索引',
    'settings.embeddings.buildIndexDesc': '索引新增和已修改的笔记。已索引的笔记会被跳过。使用“强制重建”从头重新索引全部内容。',
    'settings.embeddings.cancelIndexing': '取消索引',
    'settings.embeddings.cancelIndexingDesc': '停止当前索引任务。进度已保存到磁盘，下次构建将从上次中断处继续。',
    'settings.embeddings.deleteIndexName': '删除索引',
    'settings.embeddings.deleteIndexDesc': '移除磁盘上的索引。笔记不受影响。',
    'settings.embeddings.deleteConfirmTitle': '删除语义索引？',
    'settings.embeddings.deleteConfirmMessage': '这将永久删除索引及所有增强数据。你需要从头重建。笔记不受影响。',
    'settings.embeddings.deleteConfirmAccept': '删除索引',
    'settings.embeddings.checkpointInterval': '检查点间隔',
    'settings.embeddings.checkpointIntervalDesc': '每索引多少个文件向磁盘保存一次进度。越小 = 检查点越频繁，慢盘更安全。越大 = 写入更少，略快。默认：50。',
    'settings.embeddings.chunkSize': '分块大小',
    'settings.embeddings.chunkSizeDesc': '索引笔记时每块的字符数。越小 = 结果更精确、分块更多。越大 = 每块上下文更多、API 调用更少。更改此项会触发完整索引重建。',
    'settings.embeddings.hyde': '`HyDE`（假设文档嵌入）',
    'settings.embeddings.hydeDesc': '搜索前先让模型写一段能回答查询的假设笔记，再对它进行嵌入，而非直接嵌入原始查询。可提升模糊或抽象问题的召回率。每次 semantic_search 多一次模型调用。',
    'settings.embeddings.autoIndexOnChange': '文件变更时自动索引（测试版）',
    'settings.embeddings.autoIndexOnChangeDesc': '笔记保存、创建、重命名或删除时自动重新索引。对 text-embedding-3-small 等 API 嵌入模型是安全的。',
    'settings.embeddings.autoIndexStrategy': '自动索引策略',
    'settings.embeddings.autoIndexStrategyDesc': '何时自动重建索引。“启动时”适合活跃知识库。“从不”则让你在聊天省略号菜单中手动触发。',
    'settings.embeddings.excludedFolders': '排除文件夹',
    'settings.embeddings.excludedFoldersDesc': '索引时跳过的文件夹。',
    'settings.embeddings.chunkSmall': '小（800 字符），适合短小的原子笔记',
    'settings.embeddings.chunkMedium': '中（1200 字符）',
    'settings.embeddings.chunkStandard': '标准（2000 字符），默认',
    'settings.embeddings.chunkLarge': '大（3000 字符），适合长日记',
    'settings.embeddings.autoIndexNever': '从不（仅手动）',
    'settings.embeddings.autoIndexStartup': '启动时',
    'settings.embeddings.autoIndexModeSwitch': '切换智能体时',
    'settings.embeddings.statusDisabled': '语义索引已禁用。',
    'settings.embeddings.statusNotInit': '未初始化。关闭再开启以重新加载。',
    'settings.embeddings.statusNotBuilt': '尚未构建。点击“构建索引”开始。',
    'settings.embeddings.statusBuilding': '正在构建索引…',
    'settings.embeddings.statusCancelling': '正在取消…',
    'settings.embeddings.statusForceRebuild': '正在强制重建…',
    'settings.embeddings.statusReady': '就绪：{{docCount}} 条笔记 · 构建于：{{builtAt}}',
    'settings.embeddings.statusBuildFailed': '构建失败：{{error}}',
    'settings.embeddings.statusRebuildFailed': '重建失败：{{error}}',
    'settings.embeddings.statusSkipped': '跳过 {{count}} 个文件',
    'settings.embeddings.noEmbeddingModel': '未配置嵌入模型。请在上方添加一个以启用语义搜索。',
    'settings.embeddings.usingModel': '使用 {{name}}（{{provider}}）作为嵌入模型。',
    'settings.embeddings.indexDesc': '为所有笔记构建本地向量索引以供 semantic_search 使用。{{embModelDesc}}',
    'settings.embeddings.quickSetupTitle': '快速设置：',
    'settings.embeddings.quickSetupStep1': '1. 点击上方“+ 添加嵌入模型”并选择一个提供商。',
    'settings.embeddings.quickSetupStep2': '2. 选择一个模型，如 text-embedding-3-small（快速、便宜、质量出色）。',
    'settings.embeddings.quickSetupStep3': '3. 输入 API 密钥，然后在下方启用语义索引。',
    'settings.embeddings.quickSetupFreeTitle': '免费方案：',
    'settings.embeddings.quickSetupFreeDesc': '本地提供商可零成本运行嵌入模型。安装本地推理服务器，拉取 nomic-embed-text，并作为本地嵌入模型在上方添加。',
    'settings.embeddings.infoIndexTitle': '语义索引',
    'settings.embeddings.infoIndexBody': '语义索引会读取你的全部笔记，把它们拆成小段，并把每段转换为对其含义的数学表示（称为“嵌入”）。当你向智能体提问时，它会按含义相似度查找笔记，而非仅匹配字词。这能显著提升智能体在你知识库中找到相关上下文的能力。',
    'settings.embeddings.infoCheckpointTitle': '检查点间隔',
    'settings.embeddings.infoCheckpointBody': '索引器每 n 个文件向磁盘保存一次检查点。若索引被中断（应用关闭、出错），下次运行会从上次检查点继续，因此只处理未索引或已修改的文件。间隔越小，中断时损失越少，但写盘更频繁。多数知识库建议 10 到 30。',
    'settings.embeddings.infoHydeTitle': '`HyDE`',
    'settings.embeddings.infoHydeBody': '假设文档嵌入是一种提升语义搜索召回率的技术。智能体不直接嵌入你的查询，而是先让模型写一段能回答你问题的短笔记，再对这段假设文本进行嵌入并用于搜索。这对“我的目标是什么？”这类模糊查询尤其有效，因为直接嵌入可能匹配不佳。代价是每次搜索多一次模型调用。',
    'settings.embeddings.infoAutoChangeTitle': '变更时自动索引',
    'settings.embeddings.infoAutoChangeBody': '启用后，你停止输入 2 秒后就会重新嵌入被编辑的文件。与基于 API 的嵌入模型配合良好。',
    'settings.embeddings.infoAutoStrategyTitle': '自动索引策略',
    'settings.embeddings.infoAutoStrategyBody': '“启动时”在每次打开 Obsidian 时重建索引。保持索引新鲜，但大型知识库会延长几秒启动时间。“切换智能体时”在你切换智能体时重建，适合每个智能体处理知识库不同部分的情况。“从不”表示你通过聊天省略号菜单中的“强制重建知识库索引”选项手动控制。',
    'settings.embeddings.infoExcludedTitle': '排除文件夹',
    'settings.embeddings.infoExcludedBody': '用于跳过含有你不希望智能体搜索的文件的文件夹（满是图片或 `PDF` 的附件文件夹、模板文件夹或私密日记）。输入相对于知识库根目录的文件夹路径，每行一个。',
    'settings.embeddings.riskNote': '风险：此设置可能拖慢知识库性能或使 Obsidian 卡顿。',
    'settings.embeddings.folderPlaceholder': '输入 / 浏览文件夹',
    'settings.embeddings.configureModel': '配置',
    'settings.embeddings.removeModel': '移除',
    // Contextual retrieval (FEATURE-1501)
    'settings.embeddings.contextualRetrieval': '上下文检索',
    'settings.embeddings.contextualRetrievalDesc': '在后台用 AI 生成的上下文增强分块。可提升 49-67% 的搜索质量。需要下方配置上下文模型。',
    'settings.embeddings.contextualModel': '上下文检索模型',
    'settings.embeddings.contextualModelDesc': '用于生成上下文前缀的对话模型。请使用便宜/快速的模型（如 Haiku、gpt-4o-mini）。',
    'settings.embeddings.contextualModelPlaceholder': '选择模型',
    'settings.embeddings.statusEnriching': '增强中：{{processed}}/{{total}} 个分块（搜索可用，质量持续提升）',
    'settings.embeddings.statusPendingEnrichment': '{{count}} 个分块待增强',
    // Graph expansion (FEATURE-1502)
    'settings.embeddings.headingGraph': '图谱扩展',
    'settings.embeddings.sectionGraphInfo': '语义搜索找到最相关笔记后，图谱扩展会沿 wikilink 和标签再走一步，拉取相关上下文。当最相关的笔记只是一个指向真正内容的存根时很有用。每次搜索多几次读取。',
    'settings.embeddings.graphExpansion': '图谱扩展',
    'settings.embeddings.graphExpansionDesc': '通过 wikilink 和内容地图属性扩展搜索结果。把你的知识库图谱提取到知识数据库中。',
    'settings.embeddings.expansionHops': '扩展跳数',
    'settings.embeddings.expansionHopsDesc': '跟随多少层链接（1 = 直接链接，2 = 链接的链接，3 = 广泛）。值越大包含的上下文越多。',
    'settings.embeddings.hops1': '1 跳（直接链接）',
    'settings.embeddings.hops2': '2 跳',
    'settings.embeddings.hops3': '3 跳（广泛）',
    'settings.embeddings.mocProperties': '内容地图属性名',
    'settings.embeddings.mocPropertiesDesc': '作为图谱边提取的属性（逗号分隔）。例如：topics, concepts, people。',
    'settings.embeddings.mocPropertiesPlaceholder': 'Topics, concepts, people',
    'settings.embeddings.categoryProperty': '分类属性名',
    'settings.embeddings.categoryPropertyDesc': '定义笔记类型的 frontmatter 属性（如 kategorie、category）。',
    'settings.embeddings.summaryProperty': '摘要属性名',
    'settings.embeddings.summaryPropertyDesc': '用于短摘要的 frontmatter 属性（如 zusammenfassung、summary）。',
    'settings.embeddings.sourceNaming': '来源命名约定',
    'settings.embeddings.sourceNamingDesc': '来源文件的命名约定（如 author-year_title）。',
    'settings.embeddings.graphStats': '图谱：已提取 {{edges}} 条边、{{tags}} 个唯一标签',
    'settings.embeddings.graphNotInit': '图谱：未初始化（请先启用语义索引）',
    // Implicit connections (FEATURE-1503)
    'settings.embeddings.headingImplicit': '隐式连接',
    'settings.embeddings.sectionImplicitInfo': '建议你尚未手动链接的相关笔记的 wikilink。基于嵌入向量运行，因此捕捉的是主题相似性，而非仅标题匹配。以内联提示形式浮现；不会自动改动你的笔记。',
    'settings.embeddings.implicitConnections': '隐式连接',
    'settings.embeddings.implicitConnectionsDesc': '发现没有直接链接但语义相似的笔记。在索引后于后台计算。',
    'settings.embeddings.similarityThreshold': '相似度阈值',
    'settings.embeddings.similarityThresholdDesc': '算作隐式连接的最小余弦相似度（0.5 = 宽松，0.9 = 严格）。',
    'settings.embeddings.suggestionBanner': '建议横幅',
    'settings.embeddings.suggestionBannerDesc': '在侧栏显示隐式连接建议。若建议令人分心可关闭。',
    'settings.embeddings.implicitStats': '已发现 {{count}} 条隐式连接',
    'settings.embeddings.implicitComputing': '正在计算隐式连接…',
    'settings.embeddings.implicitNone': '尚未计算隐式连接（请先构建索引）',
    // Local reranking (FEATURE-1504)
    'settings.embeddings.headingReranking': '本地重排',
    'settings.embeddings.sectionRerankingInfo': '用一个小型本地模型对顶部搜索结果重新排序的第二道工序。嵌入快但粗；当首个结果“看起来相似”但并非你真正想要的时，重排器会修正明显的排序错误。完全离线运行。',
    'settings.embeddings.localReranking': '本地重排',
    'settings.embeddings.localRerankingDesc': '用本地交叉编码器模型对搜索结果重新打分。完全在设备上运行，仅限桌面端。',
    'settings.embeddings.rerankCandidates': '重排候选数',
    'settings.embeddings.rerankCandidatesDesc': '重排多少个候选（更多 = 质量更好但更慢）。',

    // =========================================================================
    // Settings — Web Search Tab
    // =========================================================================
    'settings.webSearch.introTitle': '网络访问',
    'settings.webSearch.introDesc': '当智能体需要知识库中没有的信息时使用。添加搜索提供商（Tavily、Brave）以进行关键词搜索；网页抓取无需密钥即可工作。',
    'settings.webSearch.desc': '配置 web_fetch（读取任意 URL）和 web_search（关键词搜索）；web_fetch 无需 API 密钥，web_search 需要一个。',
    'settings.webSearch.headingGeneral': '通用',
    'settings.webSearch.sectionGeneralInfo': '智能体在 Obsidian 之外所做一切的总开关。关闭后，无论其他设置如何，智能体都无法抓取 URL 或执行搜索。开启后，仍会遵守“权限”下的自动批准规则。',
    'settings.webSearch.headingProvider': '搜索提供商',
    'settings.webSearch.sectionProviderInfo': '选择由谁来响应关键词搜索。Tavily 和 Brave 各需自己的 API 密钥。未配置提供商时，智能体仍可抓取指定的 URL，只是无法按主题发现新页面。',
    'settings.webSearch.enableWebTools': '启用网络工具',
    'settings.webSearch.enableWebToolsDesc': '允许智能体抓取网页并执行互联网搜索。关闭以让智能体完全在知识库内工作。',
    'settings.webSearch.provider': '提供商',
    'settings.webSearch.providerDesc': '智能体用于关键词搜索的服务。若只需抓取指定 `URL` 而非执行搜索查询，选择“无”。',
    'settings.webSearch.braveKey': 'Brave 搜索 API 密钥',
    'settings.webSearch.braveKeyDesc': 'Brave 搜索所需。在 brave.com/search/api 获取免费 API 密钥（免费计划每月 2,000 次搜索）。',
    'settings.webSearch.tavilyKey': 'Tavily API 密钥',
    'settings.webSearch.tavilyKeyDesc': 'Tavily 搜索所需。在 tavily.com 获取免费 API 密钥（免费计划每月 1,000 次搜索）。',
    'settings.webSearch.providerNone': '无（仅 web_fetch）',
    'settings.webSearch.providerBrave': 'Brave 搜索',
    'settings.webSearch.providerTavily': 'Tavily',
    'settings.webSearch.bravePlaceholder': '`BSA`...',
    'settings.webSearch.tavilyPlaceholder': 'Tvly-...',

    // =========================================================================
    // Settings — MCP Tab
    // =========================================================================
    'settings.mcp.introTitle': '外部工具',
    'settings.mcp.introDesc': '连接 Obsidian 之外的工具和数据源（日历、Slack、GitHub、你自己的脚本）。每个服务器会新增智能体可调用的工具。采用 MCP 标准。',
    'settings.mcp.desc': '通过模型上下文协议连接外部工具和数据源。每个服务器暴露的工具可由智能体用 `use_mcp_tool` 调用。',
    'settings.mcp.addServer': '添加服务器',
    'settings.mcp.disconnect': '断开',
    'settings.mcp.retry': '重试',
    'settings.mcp.connect': '连接',
    'settings.mcp.saveConnect': '保存并连接',
    'settings.mcp.empty': '未配置服务器。点击“添加服务器”开始。',
    'settings.mcp.editServer': '编辑服务器：{{name}}',
    'settings.mcp.addServerTitle': '添加服务器',
    'settings.mcp.namePlaceholder': '服务器名称（如 “filesystem”）',
    'settings.mcp.commandPlaceholder': '示例：npx',
    'settings.mcp.argsPlaceholder': '如 -y @modelcontextprotocol/server-filesystem /path',
    'settings.mcp.urlPlaceholder': '如 http://localhost:3000/sse',
    'settings.mcp.timeoutPlaceholder': '60',
    'settings.mcp.labelCommand': '命令',
    'settings.mcp.labelArgs': '参数（空格分隔）',
    'settings.mcp.labelEnv': '环境变量（key=value，每行一个）',
    'settings.mcp.labelUrl': 'URL',
    'settings.mcp.labelHeaders': '请求头（key=value，每行一个）',
    'settings.mcp.labelTimeout': '超时（秒）',
    'settings.mcp.toolCount': '{{count}} 个工具',
    'settings.mcp.edit': '编辑',
    'settings.mcp.delete': '删除',
    'settings.mcp.builtInDisabledHint': '需要 API 密钥。点击编辑进行配置，再连接。',

    // =========================================================================
    // Settings — Modes Tab
    // =========================================================================
    'settings.modes.introTitle': '什么是智能体？',
    'settings.modes.introDesc': '智能体是你的助手所扮演的人格：它的系统提示词（游戏规则）、可使用的工具集，以及你给它的额外指令。在此切换智能体会立即改变助手的思考方式与能力。默认智能体为读/写、完整工具集。可自建以专精（如只读研究、专注写作、代码审查）。',
    'settings.modes.groupBuiltIn': '默认',
    'settings.modes.groupGlobal': '跨知识库共享',
    'settings.modes.groupVault': '此知识库中的智能体',
    'settings.modes.newMode': '+ 新建智能体',
    'settings.modes.duplicate': '+ 复制',
    'settings.modes.duplicated': '已创建“{{name}}”并切换至它。',
    'settings.modes.duplicateFailed': '无法复制：找不到智能体。',
    'settings.modes.import': '导入',
    'settings.modes.done': '完成',
    'settings.modes.previewPrompt': '显示完整系统提示词',
    'settings.modes.export': '导出',
    'settings.modes.restoreDefaults': '恢复默认',
    'settings.modes.delete': '删除',
    'settings.modes.deleteBuiltInTooltip': '默认智能体无法删除。请复制它再编辑副本。',
    'settings.modes.deleted': '已删除“{{name}}”。',
    'settings.modes.name': '名称',
    'settings.modes.shortDesc': '描述',
    'settings.modes.shortDescHint': '智能体在决定是否切换时会通过 switch_agent 工具看到它。不会在聊天中向你显示。',
    'settings.modes.shortDescPlaceholder': '简短描述…',
    'settings.modes.roleDefinition': '系统提示词（角色）',
    'settings.modes.roleDefinitionHint': '智能体会把这段作为系统提示词的第一部分读取。它定义了智能体是谁、做什么、如何工作。用下方“显示完整系统提示词”查看拼装结果。',
    'settings.modes.customInstructions': '附加指令（可选）',
    'settings.modes.customInstructionsHint': '追加在角色之后。用于微调（特定语气、输出格式、要避免的事）而无需重写整个角色。',
    'settings.modes.customInstructionsPlaceholder': '为 {{mode}} 添加行为准则…',
    'settings.modes.globalInstructionsPlaceholder': '示例：始终用中文回复。绝不使用超过 5 项的列表。',
    'settings.modes.customized': '你已自定义此智能体',
    'settings.modes.loading': '加载中…',
    'settings.modes.activeMode': '活动智能体',
    'settings.modes.globalCustomInstructions': '对所有智能体的指令',
    'settings.modes.globalCustomInstructionsDesc': '叠加在每个智能体的系统提示词之上。用于知识库范围的偏好（你的语言、格式规则、绝不希望出现的内容）。',
    'settings.modes.fileTooLarge': '智能体文件过大（上限 500 KB）',
    'settings.modes.invalidJson': '无效的智能体文件：不是合法 JSON',
    'settings.modes.invalidMode': '无效的智能体文件：缺少 slug、名称或系统提示词',
    'settings.modes.parseFailed': '解析智能体文件失败',
    'settings.modes.importSuccess': '智能体“{{name}}”已导入',
    'settings.modes.restored': '{{name}} 已恢复为默认',

    // =========================================================================
    // Settings — Permissions Tab
    // =========================================================================
    'settings.permissions.introTitle': '批准操作（请仔细审阅）',
    'settings.permissions.introDesc': '下方每个自动批准的类别都会让智能体在不再次询问的情况下作用于你的知识库、数据或外部世界。请有意地设置每个开关，并在更换模型、安装新 MCP 服务器或赋予智能体更广技能时重新审阅。最高风险的组合是：网络访问 + 写入访问（智能体可抓取并执行来自互联网的任何内容），以及沙箱代码执行（LLM 编写并在你的浏览器中运行的代码）。仅在信任当前模型与提示词时才自动批准这些。',
    'settings.permissions.desc': '自动批准控制智能体是可以立即执行操作还是必须先征得你的确认。某类别关闭时，智能体在该类别的每次操作前都会暂停并显示批准对话框。',
    'settings.permissions.headingBehavior': '智能体行为',
    'settings.permissions.headingAutoApprove': '自动批准',
    'settings.permissions.sectionAutoApproveInfo': '下方一切的总开关。开启时，智能体对你已许可的类别无需询问即运行。关闭时，每次工具调用都会在聊天中显示确认。若你同时允许网络 + 写入，宽松模式警告会亮起——这是最高风险组合（智能体可抓取任意来源内容并未经你审阅即执行）。',
    'settings.permissions.headingPerCategory': '按类别',
    'settings.permissions.sectionPerCategoryInfo': '哪些类别的工具调用自动批准。读取最安全（文件读取、搜索），笔记编辑和知识库变更会触及你的文件，网络从外部抓取内容，子智能体会派生继承相同规则的智能体。此处关闭的任何类别都会在智能体运行前于聊天中显示确认。',
    'settings.permissions.headingPluginApi': '插件 API 与配方',
    'settings.permissions.sectionPluginApiInfo': '专门针对外部命令面（其他 Obsidian 插件和配方运行器）的批准规则。插件读取调用是安全的；插件写入调用和配方会触及你的数据或运行外部程序，因此默认关闭。',
    'settings.permissions.enableAutoApprove': '启用自动批准',
    'settings.permissions.enableAutoApproveDesc': '主开关。关闭时，无论下方各项设置如何，你都必须手动确认每个操作。',
    'settings.permissions.showApprovalBar': '在聊天中显示批准栏',
    'settings.permissions.showApprovalBarDesc': '在聊天输入框上方显示一行快速切换按钮，便于访问。',
    'settings.permissions.readOps': '读取操作',
    'settings.permissions.readOpsDesc': '读取和搜索笔记。这些操作绝不改变你的知识库。',
    'settings.permissions.noteEdits': '笔记编辑',
    'settings.permissions.noteEditsDesc': '写入或更改笔记内容。关闭时，每次编辑在保存前都要审阅确认。',
    'settings.permissions.vaultChanges': '知识库结构变更',
    'settings.permissions.vaultChangesDesc': '创建文件夹、移动文件、删除笔记、生成画布或创建数据库。较难撤销。',
    'settings.permissions.webOps': '网络操作',
    'settings.permissions.webOpsDesc': '智能体可代你打开网页并执行网络搜索。',
    'settings.permissions.mcpCalls': '协议工具调用',
    'settings.permissions.mcpCallsDesc': '智能体可使用你通过第三方集成（协议服务器）连接的外部工具。',
    'settings.permissions.modeSwitching': '模式切换',
    'settings.permissions.modeSwitchingDesc': '让智能体无需询问即可在模式间切换。',
    'settings.permissions.subtasks': '子任务',
    'settings.permissions.subtasksDesc': '允许智能体创建辅助智能体，独立处理更大任务的子部分。',
    'settings.permissions.followUp': '追问',
    'settings.permissions.followUpDesc': '让智能体在任务过程中向你提出澄清问题，无需单独批准。',
    'settings.permissions.todoUpdates': '待办列表更新',
    'settings.permissions.todoUpdatesDesc': '允许智能体在工作时更新其任务清单。',
    'settings.permissions.pluginSkills': '插件技能',
    'settings.permissions.pluginSkillsDesc': '运行 Obsidian 命令、启用或禁用插件，并使用 PDF 导出等内置功能。',
    'settings.permissions.pluginApiReads': '插件 API 读取',
    'settings.permissions.pluginApiReadsDesc': '让智能体从其他插件（如 Dataview、omnisearch）读取数据。绝不改变你的知识库。',
    'settings.permissions.pluginApiWrites': '插件 API 写入',
    'settings.permissions.pluginApiWritesDesc': '让智能体通过其他插件（如 `MetaEdit`）更改数据。出于安全默认关闭。',
    'settings.permissions.recipes': '配方执行',
    'settings.permissions.recipesDesc': '让智能体无需询问即运行导出配方（如 Pandoc）。默认关闭。',

    // Security warnings for high-risk auto-approval toggles
    'settings.permissions.enableAutoApproveWarning': '启用后，智能体会先斩后奏。你将失去在操作发生前审阅的机会。仅启用你完全信任的类别。',
    'settings.permissions.noteEditsWarning': '智能体可在不询问的情况下更改你的笔记。你将无法分辨某处改动是有意为之还是受误导输入所致。',
    'settings.permissions.vaultChangesWarning': '删除或移动文件难以撤销。检查点系统可帮助恢复变更，但仍建议人工审阅。',
    'settings.permissions.webOpsWarning': '智能体会打开网页并在外部服务器上执行搜索。来自不可信站点的内容可能影响智能体行为。',
    'settings.permissions.mcpCallsWarning': '外部工具可在其连接的服务器上执行任意操作。仅在你信任所有已连接集成时才启用。',
    'settings.permissions.pluginApiWritesWarning': '智能体通过其他插件更改数据，享有这些插件同样的访问权限。',
    'settings.permissions.recipesWarning': '配方会在你的电脑上运行程序。启用此项会移除执行前的最后一道人工检查。',
    'settings.permissions.subtasksWarning': '辅助智能体使用相同的自动批准设置，可无需单独确认即行动。',

    // Sandbox execution
    'settings.permissions.headingSandbox': '沙箱代码执行',
    'settings.permissions.sectionSandboxInfo': '智能体偶尔会在隔离沙箱内运行少量 TypeScript（无 Node.js API、无文件系统访问，仅有 Vault Operator 暴露的内容）。自动批准会跳过确认步骤。风险较高，因为代码由 LLM 编写；仅在信任当前模型与提示词时才启用。',
    'settings.permissions.sandbox': '自动批准沙箱执行',
    'settings.permissions.sandboxDesc': '让智能体无需询问即在受保护沙箱中运行代码。默认关闭。你的确认是抵御有害代码的主要屏障。',
    'settings.permissions.sandboxWarning': '智能体可在 `sandbox` 中运行任意代码，沙箱提供基本保护但并未与应用其余部分完全隔离。误导输入可能导致有害代码未经你审阅即运行；除非你完全理解风险，否则保持关闭。',
    'settings.permissions.sandboxConfirmTitle': '启用沙箱自动批准？',
    'settings.permissions.sandboxConfirmMessage': '这将允许智能体在未经你审阅的情况下运行代码。沙箱提供基本保护但并未完全隔离。来自网页或知识库笔记的内容可能导致未审阅的代码运行。确定吗？',
    'settings.permissions.sandboxConfirmCancel': '取消',
    'settings.permissions.sandboxConfirmAccept': '我了解风险，启用',

    // H-1: Permissive mode warning (web + writes both auto-approved)
    'settings.permissions.permissiveWarning': '宽松模式：网络访问与写入操作均已自动批准。来自不可信网页或知识库笔记的内容可能诱骗智能体未经审阅即修改你的知识库。这是最高风险配置。考虑禁用网络访问或写入操作的自动批准之一。',

    // =========================================================================
    // Settings — Loop Tab
    // =========================================================================
    'settings.loop.introTitle': '运行行为',
    'settings.loop.introDesc': '智能体持续工作多久、容忍多少错误、何时对对话做摘要以保持专注。默认值已较为合理；仅在有具体理由时调整。',

    // Limits & retries
    'settings.loop.headingLoop': '限制与重试',
    'settings.loop.sectionLoopDesc': '在智能体烧光 token 或无限运行之前把它拦下的安全网。每项独立触发。',
    'settings.loop.errorLimit': '错误上限',
    'settings.loop.errorLimitDesc': '连续工具错误达到此数后停止。默认：3。设为 0 表示永不自动停止。',
    'settings.loop.rateLimit': '请求间暂停',
    'settings.loop.rateLimitDesc': 'API 调用之间等待的毫秒数。默认：0。仅当提供商频繁返回限流错误时才提升到 500-1500 毫秒。',
    'settings.loop.maxIterations': '每条消息步数',
    'settings.loop.maxIterationsDesc': '智能体对一条消息可进行的工具调用轮数。默认：25。',
    'settings.loop.maxIterationsInfo': '一步 = 智能体生成一次回复、调用一个或多个工具并等待结果。多步任务（研究、重构、深度摄入）需要很多步。若在复杂任务上频繁看到“已达最大迭代次数”提示，可提升到 50。',
    'settings.loop.maxSubtaskDepth': '子智能体深度',
    'settings.loop.maxSubtaskDepthDesc': '子智能体可嵌套的深度。默认：2。',
    'settings.loop.maxSubtaskDepthInfo': '子智能体是主智能体可为某子任务派生的第二个智能体（如“并行研究这个”）。深度 1 表示子智能体不能再派生子智能体；2 允许多一层。每层都新增一份系统提示词，token 成本倍增；更深的树很少改善结果。',

    // Auto-summarise
    'settings.loop.headingCondensing': '自动摘要',
    'settings.loop.sectionCondensingDesc': 'AI 模型一次能持有的文本量有限。当聊天接近该上限时，智能体会自动把较早的消息压缩为回顾，以便在单个长任务上继续。摘要会替换原始消息，因此最近几轮之前的任何内容都是转述而非逐字。',
    'settings.loop.enableCondensing': '自动摘要长聊天',
    'settings.loop.enableCondensingDesc': '聊天填满后用回顾替换较早的消息。默认：开。',
    'settings.loop.condensingThreshold': '触发阈值',
    'settings.loop.condensingThresholdDesc': '聊天达到内存上限的此比例时做摘要。默认：80 %。',

    // Power steering
    'settings.loop.headingPowerSteering': '强力引导',
    'settings.loop.sectionPowerSteeringDesc': '在长任务上，智能体可能因角色定义（系统提示词）在对话中位置靠后而偏离指令。强力引导会周期性重发角色，让智能体保持人设。',
    'settings.loop.powerSteeringFreq': '刷新频率',
    'settings.loop.powerSteeringFreqDesc': '每 N 轮重发一次角色。默认：4。设为 0 禁用。',

    // Task routing
    'settings.loop.headingHelperModel': '任务路由',
    'settings.loop.sectionRoutingDesc': '某些提示（创建一个 XLSX、摘要单条笔记、重命名文件夹）不需要旗舰模型。Vault Operator 可检测这些并自动路由到更便宜的经济档模型，若经济模型吃力则回退到主模型。',
    'settings.loop.autoTaskRouterName': '把简单任务路由到经济档',
    'settings.loop.autoTaskRouterDesc': '单步提示使用经济档模型。多步提示留在主模型。默认：开。',
    'settings.loop.leanSystemPromptName': '精简系统提示词',
    'settings.loop.leanSystemPromptDesc': '始终使用紧凑版提示词以节省 token。可能略微降低插件技能感知，直到技能被提及。默认：关。',

    // =========================================================================
    // Settings — Memory Tab
    // =========================================================================
    'settings.memory.introTitle': '长期记忆',
    'settings.memory.introDesc': '智能体跨会话记住关于你和项目的事实。可编辑其存储内容或关闭提取。',
    'settings.memory.desc': '配置智能体如何记住对话并从过往交互中学习。记忆由专用模型在后台提取。',
    'settings.memory.headingHistory': '聊天历史',
    'settings.memory.sectionHistoryInfo': '每段对话是否保留并显示在历史侧栏。关 = 关闭聊天即消失；开 = 可搜索并可喂给记忆提取。',
    'settings.memory.headingMemory': '记忆',
    'settings.memory.sectionMemoryInfo': '自动提取开启时，已结束的对话会被摘要为智能体存储的关于你和项目的离散事实。这些事实一旦相关就会被拉入下一段聊天的上下文。关闭以保持记忆完全手动：除非你在聊天中明说（“记住……”），否则什么都不存。',
    'settings.memory.headingModel': '记忆模型',
    'settings.memory.headingThreshold': '提取阈值',
    'settings.memory.headingFiles': '记忆文件',
    'settings.memory.headingOnboarding': '引导',
    'settings.memory.sectionOnboardingInfo': '一段简短的引导对话，询问基本信息（你是谁、做什么、你的偏好），让智能体在第一天有据可依。可随时重跑以从零刷新画像。',
    'settings.memory.headingCrossSurface': '跨端同步',
    'settings.memory.sectionCrossSurfaceInfo': '外部聊天工具（ChatGPT、Claude.ai、Claude Code、Perplexity）通过远程 MCP 把对话推送到 Vault Operator。你在这些工具中触发每次推送（例如在 ChatGPT 里“保存到记忆”）；Vault Operator 只决定数据到达后如何处理：立即提取记忆，还是作为待定对话搁置，直到你在历史侧栏中审阅。ChatGPT 和 Perplexity 默认为待定，以避免家庭共享账户混入个人记忆。',
    'settings.memory.crossSurfaceInlineHint': '外部工具（ChatGPT、Claude.ai、Claude Code、Perplexity）会自行通过 MCP 把对话推送到 Vault Operator。你在这些工具内触发每次推送，从不在此时此地进行。下方设置仅决定 Vault Operator 在推送到达后做什么：立即提取记忆，还是作为待定对话搁置供你在历史侧栏中审阅。',
    'settings.memory.crossSurfaceInactiveTitle': '跨端同步未激活。',
    'settings.memory.crossSurfaceInactiveBody': '未启用任何远程 MCP 服务器，因此外部工具尚无法把对话推送到 Vault Operator。在“自定义 → 连接器”下启用一个连接器，并将外部工具指向其端点以开始接收推送。设置好后，处理规则会出现在此处。',
    'settings.memory.headingContents': '记忆内容',
    'settings.memory.sectionContentsInfo': '查看智能体记得关于你的内容以及它如何自知。要添加条目，在聊天中直接说（如“记住不要使用表情符号”）。用此视图检查存储内容并移除你不希望保留的条目。',
    'settings.memory.viewMemory': '查看记忆',
    'settings.memory.viewMemoryDesc': '浏览用户事实、智能体灵魂和能力快照。可在此软删除。',
    'settings.memory.viewMemoryButton': '打开',
    'settings.memory.deleteAll': '删除全部记忆',
    'settings.memory.deleteAllDesc': '永久移除用户记忆、智能体灵魂、会话和审计日志中的所有条目。需要输入确认词。',
    'settings.memory.deleteAllButton': '全部删除',
    'settings.memory.enableHistory': '启用聊天历史',
    'settings.memory.enableHistoryDesc': '把对话保存到插件目录，便于日后浏览和恢复。',
    'settings.memory.storedConversations': '已存对话',
    'settings.memory.storedConversationsDesc': '已保存 {{count}} 段对话',
    'settings.memory.enableMemory': '启用记忆',
    'settings.memory.enableMemoryDesc': '允许智能体从对话中构建长期记忆。禁用以停止所有提取。',
    'settings.memory.autoExtract': '自动提取会话摘要',
    'settings.memory.autoExtractDesc': '对话结束时自动提取记忆。星标按钮和“记住这个”智能体提示无论此设置如何始终有效。',
    'settings.memory.manualAlwaysHint': '你始终可手动保存：让智能体（“记住这个”）或点击某段对话的星标按钮。',
    'settings.memory.modelSelect': '记忆提取模型',
    'settings.memory.modelSelectDesc': '选择一个小而快的模型（如 haiku）以低成本在后台提取。',
    'settings.memory.noModels': '未配置模型。请先在提供商中添加并启用一个模型。',
    'settings.memory.minMessages': '提取前的最少消息数',
    'settings.memory.minMessagesDesc': '短于此长度的对话不保存到记忆。',
    'settings.memory.memoryStorage': '记忆存储',
    'settings.memory.memoryStorageLoading': '加载中…',
    'settings.memory.userProfile': '用户画像',
    'settings.memory.noProfile': '尚无画像。开始一段对话，智能体会引导你完成设置。',
    'settings.memory.profileActive': '画像已激活。智能体使用你的偏好来个性化回复。',
    'settings.memory.setupDialog': '设置对话框',
    'settings.memory.setupCompleted': '设置已完成。重启以重新配置模型、权限和画像。',
    'settings.memory.setupNotStarted': '尚未开始设置。打开聊天即可开始。',
    'settings.memory.clearAll': '全部清除',
    'settings.memory.viewFiles': '查看文件',
    'settings.memory.resetAll': '全部重置',
    'settings.memory.restartSetup': '重新开始设置',
    'settings.memory.startSetup': '开始设置',
    'settings.memory.skipSetup': '跳过设置',
    'settings.memory.selectModel': '选择模型',
    'settings.memory.allConversationsDeleted': '所有对话已删除',
    'settings.memory.memoryFilesLocation': '记忆文件：{{dir}}',
    'settings.memory.allMemoryReset': '所有记忆文件已重置',
    'settings.memory.setupSkipped': '已跳过设置。你可随时从设置中重新开始。',
    'settings.memory.statsFiles': '{{count}} 个记忆文件',
    'settings.memory.statsSessions': '{{count}} 段会话摘要',
    'settings.memory.statsLastUpdated': '最后更新于 {{date}}',

    // =========================================================================
    // Settings — Rules Tab
    // =========================================================================
    'settings.rules.heading': '规则',
    'settings.rules.desc': '规则会注入到每个智能体会话的系统提示词中。以 .md 或 .txt 形式存放在知识库的 .obsidian-agent/rules/ 目录。',
    'settings.rules.introTitle': '规则',
    'settings.rules.introDesc': '每个智能体都遵守的内部规则。用于语气、格式偏好或“绝不做 X”。叠加在每个智能体自身指令之上。',
    'settings.rules.introDiff': '区别：技能是反应式行为（仅在相关时激活）。工作流是带斜杠命令的具体序列。规则是始终生效的被动原则。',
    'settings.rules.placeholder': '规则名（如 “always-use-iso-dates”）',
    'settings.rules.create': '创建规则',
    'settings.rules.import': '导入',
    'settings.rules.loaderNotAvailable': '规则加载器不可用。',
    'settings.rules.empty': '尚无规则。在上方创建一个。',
    'settings.rules.editRule': '编辑规则：{{name}}',
    'settings.rules.edit': '编辑',
    'settings.rules.export': '导出',
    'settings.rules.delete': '删除',
    'settings.rules.importFailed': '无法导入规则',

    // =========================================================================
    // Settings — Workflows Tab
    // =========================================================================
    'settings.workflows.heading': '工作流',
    'settings.workflows.desc': '在聊天中输入 /workflow-name 触发工作流。以 .md 或 .txt 形式存放在知识库的 .obsidian-agent/workflows/ 目录。',
    'settings.workflows.introTitle': '工作流',
    'settings.workflows.introDesc': '可复用的多步例程。在聊天中用斜杠命令触发（如 `/weekly-review`），智能体会运行整个序列。',
    'settings.workflows.introDiff': '区别：工作流是显式由用户触发的序列（通过 /workflow-name）。技能在相关时自动激活。规则是被动原则。工具执行单个操作。',
    'settings.workflows.placeholder': '工作流名（如 “daily-review”）',
    'settings.workflows.create': '创建工作流',
    'settings.workflows.import': '导入',
    'settings.workflows.loaderNotAvailable': '工作流加载器不可用。',
    'settings.workflows.empty': '尚无工作流。在上方创建一个。',
    'settings.workflows.editWorkflow': '编辑工作流：{{name}}',
    'settings.workflows.edit': '编辑',
    'settings.workflows.export': '导出',
    'settings.workflows.delete': '删除',
    'settings.workflows.importFailed': '无法导入工作流',

    // =========================================================================
    // Settings — Skills Tab
    // =========================================================================
    'settings.skills.introTitle': '技能',
    'settings.skills.introDesc': '智能体按需为特定任务类型加载的分步指南（如“摄入一个 PDF”、“起草会议纪要”）。智能体根据你的请求来挑选。',
    'settings.skills.introDiff': '关键区别：工具执行操作（读文件、搜索、编辑）。技能提供指令（如何处理会议笔记、项目规划等）。工作流定义固定的分步序列。',
    'settings.skills.headingManual': '用户技能',
    'settings.skills.headingPlugin': '插件技能',
    'settings.skills.desc': '技能在与用户消息相关时自动注入系统提示词。每个技能位于 .obsidian-agent/skills/{name}/SKILL.md 的子文件夹中，带 frontmatter：name、description。',
    'settings.skills.pluginDisabled': '插件技能已禁用。在高级设置中启用 `VaultDNA` 以自动发现 Obsidian 插件作为智能体技能。',
    'settings.skills.pluginStats': '从已安装的 Obsidian 插件自动发现。活动：{{active}} | 禁用：{{disabled}} | 总计：{{total}}',
    'settings.skills.placeholder': '技能名（如 “daily-template”）',
    'settings.skills.create': '创建技能',
    'settings.skills.import': '导入',
    'settings.skills.rescan': '重新扫描知识库',
    'settings.skills.scanning': '扫描中…',
    'settings.skills.headerSkill': '技能',
    'settings.skills.headerPlugin': '插件',
    'settings.skills.headerCommands': '命令',
    'settings.skills.headerAgent': '智能体',
    'settings.skills.managerNotAvailable': '技能管理器不可用。',
    'settings.skills.empty': '尚无技能。在上方创建一个。',
    'settings.skills.editSkill': '编辑技能：{{name}}',
    'settings.skills.skillDetail': '技能：{{name}}',
    'settings.skills.readme': 'README：{{name}}',
    'settings.skills.edit': '编辑',
    'settings.skills.export': '导出',
    'settings.skills.delete': '删除',
    'settings.skills.editFile': '编辑技能文件',
    'settings.skills.viewReadme': '查看 readme',
    'settings.skills.noReadme': '无可用 readme',
    'settings.skills.installed': '已安装并启用',
    'settings.skills.disabled': '在 Obsidian 中已禁用',
    'settings.skills.importFailed': '无法导入技能',
    'settings.skills.createFailed': '无法创建技能',
    'settings.skills.deleteFailed': '无法删除技能文件',
    'settings.skills.scanComplete': 'VaultDNA：已扫描 {{count}} 个插件',
    'settings.skills.scanFailed': '`VaultDNA` 扫描失败',
    'settings.skills.fileNotFound': '找不到技能文件：{{id}}.skill.md',
    'settings.skills.noReadmeAvailable': '{{name}} 无可用 README。运行“重新扫描知识库”以获取 README。',
    'settings.skills.corePlugins': '核心插件技能（{{count}}）',
    'settings.skills.communityPlugins': '社区插件技能（{{count}}）',

    // =========================================================================
    // Settings — Prompts Tab
    // =========================================================================
    'settings.prompts.heading': '提示词',
    'settings.prompts.desc': '创建你自己的提示词模板。在聊天中输入 / 触发。用 {{userInput}} 插入当前消息文本，用 {{activeFile}} 插入活动笔记名称。',
    'settings.prompts.introTitle': '提示词',
    'settings.prompts.introDesc': '可用斜杠命令触发的可复用文本片段。插入模板化问题（如 `/translate`）并自动填充活动笔记。',
    'settings.prompts.introDiff': '区别：提示词是无逻辑的纯文本模板。工作流是结构化序列。技能是带条件的自适应行为。规则是静态约束。',
    'settings.prompts.namePlaceholder': '提示词名（如 “daily-report”）',
    'settings.prompts.formName': '名称（如 “daily report”）',
    'settings.prompts.formSlug': 'Slug（如 “daily-report”）',
    'settings.prompts.formTemplate': '提示词模板（使用 {{userInput}} 和 {{activeFile}}）',
    'settings.prompts.create': '创建提示词',
    'settings.prompts.import': '导入',
    'settings.prompts.save': '保存',
    'settings.prompts.cancel': '取消',
    'settings.prompts.newPrompt': '新提示词',
    'settings.prompts.editPrompt': '编辑提示词',
    'settings.prompts.variables': '变量：{{userInput}} = 当前聊天消息  |  {{activeFile}} = 活动笔记名称',
    'settings.prompts.modeLabel': '模式（可选）：',
    'settings.prompts.modeAll': '所有模式',
    'settings.prompts.modeHint': '把此提示词限定到特定模式。留空则在所有模式中显示。',
    'settings.prompts.empty': '尚无自定义提示词。在上方创建一个。',
    'settings.prompts.edit': '编辑',
    'settings.prompts.export': '导出',
    'settings.prompts.delete': '删除',
    'settings.prompts.invalidFile': '无效的提示词文件：缺少名称、slug 或内容',
    'settings.prompts.importFailed': '无法导入提示词',

    // =========================================================================
    // Settings — Interface Tab
    // =========================================================================
    'settings.interface.introTitle': '界面',
    'settings.interface.introDesc': '你日常看到的聊天行为：键盘快捷键、自动附加打开的笔记、聊天历史保存位置。',
    'settings.interface.headingSetup': '设置对话框',
    'settings.interface.sectionSetupInfo': '首次打开聊天时运行的简短引导：选模型、设权限、配置记忆。可随时重跑以从零重新配置。',
    'settings.interface.headingInterface': '聊天行为',
    'settings.interface.sectionInterfaceInfo': '聊天的日常控制：键盘快捷键、消息自动附带哪些上下文，以及上下文窗口进度条。',
    'settings.interface.headingHistory': '聊天历史',
    'settings.interface.sectionHistoryInfo': '聊天历史存放在哪。默认仅存于内存，应用重载即丢失。指向某个知识库文件夹后，每段对话会保存为 JSON 文件，可从省略号菜单重新打开。',
    'settings.interface.showContextProgress': '显示上下文进度',
    'settings.interface.showContextProgressDesc': '显示进度条，表明模型上下文窗口已用多少。重启侧栏以应用。',
    'settings.interface.restartSidebarNotice': '请重启侧栏（关闭后重新打开）以应用更改。',
    'settings.interface.guidedSetup': '引导式设置',
    'settings.interface.setupCompleted': '设置已完成。重启以重新配置模型、权限和画像。',
    'settings.interface.setupNotStarted': '尚未开始设置。打开聊天即可开始。',
    'settings.interface.memoryNotAvailable': '记忆服务不可用。启用记忆以使用设置对话框。',
    'settings.interface.autoAddActiveNote': '自动把活动笔记作为上下文',
    'settings.interface.autoAddActiveNoteDesc': '自动把你正在编辑器中打开的笔记附加到每条发送的消息。智能体可查看并引用其内容。',
    'settings.interface.sendWithEnter': '回车发送',
    'settings.interface.sendWithEnterDesc': '按回车发送消息（Shift+Enter 换行）。关闭时用 Ctrl+Enter（Mac 上 Cmd+Enter）发送。',
    'settings.interface.includeTime': '在上下文中包含当前时刻',
    'settings.interface.includeTimeDesc': '当前日期始终会提供给智能体。开启此项还会包含确切时刻。默认关闭：时刻每次请求都变，会破坏提示词缓存，长对话成本上升。',
    'settings.interface.historyFolder': '聊天历史文件夹',
    'settings.interface.historyFolderDesc': '把每段对话作为 JSON 文件保存到此知识库文件夹。留空禁用。通过聊天省略号菜单访问已保存对话。示例：agent/history',
    'settings.interface.restartSetup': '重新开始设置',
    'settings.interface.startSetup': '开始设置',
    'settings.interface.skipSetup': '跳过设置',
    'settings.interface.historyPlaceholder': 'Agent/history',
    'settings.interface.setupSkipped': '已跳过设置。你可随时从设置中重新开始。',
    'settings.interface.headingChatLinking': '聊天链接',
    'settings.interface.sectionChatLinkingInfo': '当智能体在聊天中创建或编辑笔记时，可在笔记 frontmatter 中留下回链，指向来源聊天。当某条笔记是一段长对话的产物、你想回顾它是如何产生的时很有用。',
    'settings.interface.chatLinkingToggle': '在 frontmatter 中自动链接聊天',
    'settings.interface.chatLinkingToggleDesc': '自动把可点击的聊天引用添加到智能体创建或编辑的每条笔记的 frontmatter。禁用以保持 frontmatter 干净。',
    'settings.interface.chatLinkingModel': '命名模型',
    'settings.interface.chatLinkingModelDesc': '选择一个小而快的模型以低成本生成语义标题。留空则用前 60 个字符作为标题。',
    'settings.interface.chatLinkingNoModels': '未配置模型。请先在提供商中添加并启用一个模型。',
    'settings.interface.chatLinkingSelectModel': '无语义命名',

    // =========================================================================
    // Settings — Shell Tab
    // =========================================================================
    'settings.shell.introTitle': '外部命令',
    'settings.shell.introDesc': '让智能体运行其他插件（Dataview、Templater、Pandoc）以及少数受沙箱保护的系统命令。默认关闭。',
    'settings.shell.headingPluginApi': '插件 API',
    'settings.shell.sectionPluginApiInfo': '其他 Obsidian 插件（Dataview、Templater、MetaEdit 等）暴露了可从脚本调用的 JavaScript 函数。开启后，智能体可调用这些函数查询数据并执行操作。一切在 Obsidian 的 JavaScript 沙箱内运行，无外壳、无超出插件本身的网络调用。',
    'settings.shell.headingAllowlist': '内置允许列表',
    'settings.shell.sectionAllowlistInfo': 'Vault Operator 自带预批准的插件方法。读取方法（查询、查找）自动批准；写入方法（更改笔记或插件状态）仍需在聊天中确认。',
    'settings.shell.headingUserSafe': '用户标记为安全的方法',
    'settings.shell.sectionUserSafeInfo': '智能体在运行时发现、你在提示时标记为安全（只读）的方法。移除条目可使下次再次需要批准。',
    'settings.shell.headingRecipes': '配方',
    'settings.shell.sectionRecipesInfo': '配方用严格参数校验包装外部程序（用于 PDF/DOCX 导出的 Pandoc、用于转换的 ImageMagick 等）。它们通过 spawn 运行，绝不经过外壳，因此输入被当作数据而非命令。默认关闭；开启主开关后逐个启用每个配方。',
    'settings.shell.headingBuiltinRecipes': '内置配方',
    'settings.shell.enablePluginApi': '允许插件 API 调用',
    'settings.shell.enablePluginApiDesc': '本节一切的总开关。关 = 完全没有插件 API 调用。',
    'settings.shell.markedSafe': '标记为安全（只读），可自动批准',
    'settings.shell.enableRecipes': '允许配方',
    'settings.shell.enableRecipesDesc': '主开关。每个配方仍需在下方单独开启。',
    'settings.shell.badgeWrite': ' [写]',
    'settings.shell.badgeRead': ' [读]',
    'settings.shell.remove': '移除',

    // =========================================================================
    // Settings — Log Tab
    // =========================================================================
    'settings.log.introTitle': '活动日志',
    'settings.log.introDesc': '智能体做了什么、何时做的。保留 30 天，便于回溯任务或报告 bug。',
    'settings.log.desc': '所有工具执行的审计轨迹。日志按天存储（最多 30 天）。点击某行展开详情。',
    'settings.log.load': '加载',
    'settings.log.download': '下载',
    'settings.log.clearAll': '清除全部日志',
    'settings.log.noLogs': '暂无日志',
    'settings.log.loggerNotAvailable': '日志器不可用',
    'settings.log.noEntries': '此日期无条目。',
    'settings.log.headerTime': '时间',
    'settings.log.headerTool': '工具',
    'settings.log.headerMode': '模式',
    'settings.log.headerDuration': '耗时',
    'settings.log.headerStatus': '状态',
    'settings.log.statusOk': '正常',
    'settings.log.statusError': '错误',
    'settings.log.detailParams': '参数',
    'settings.log.detailResult': '结果',
    'settings.log.detailError': '错误',
    'settings.log.noData': '无可下载的日志数据',
    'settings.log.downloaded': '已下载日志：{{date}}',
    'settings.log.cleared': '所有操作日志已清除',
    'settings.log.durationMs': '{{ms}} 毫秒',

    // =========================================================================
    // Settings — Debug Tab
    // =========================================================================
    'settings.debug.introTitle': '调试模式',
    'settings.debug.introDesc': '在浏览器控制台（Ctrl+Shift+I）输出详细日志。出问题时开启，平时关闭。',
    'settings.debug.debugMode': '调试模式',
    'settings.debug.debugModeDesc': '向浏览器开发者控制台写入详细日志。用 Cmd+Option+I（Mac）或 Ctrl+Shift+I（Windows）打开控制台。',
    'settings.debug.optionalAssetsHeading': '可选资源',
    'settings.debug.optionalAssetsInfo': '可选的一次性下载，不放入主插件包以使其保持在 Obsidian Sync 5 MB 阈值以下。每个资源在落地到 <vault>/.vault-operator/assets/ 前都做 SHA256 校验。插件无需其中任何一个也能工作；对应工具在你点击安装前会报告“未安装”。',

    // Optional assets sub-tab
    'settings.optionalAssets.introTitle': '可选资源',
    'settings.optionalAssets.introDesc': '一次性下载，不放入主插件包以使其保持在 Obsidian Sync 5 MB 阈值以下。每个资源在落地到 <vault>/.vault-operator/assets/ 前都做 SHA256 校验。插件无需其中任何一个也能工作；对应工具在你点击安装前会报告“未安装”。',
    'settings.optionalAssets.headingOffice': '办公套件',
    'settings.optionalAssets.sectionOfficeInfo': '打包了 exceljs、docx 和 pptxgenjs（约 1.7 MB）。创建或读取 .xlsx / .docx / .pptx 文件所需。没有它，create_xlsx / create_docx / create_pptx 工具保持禁用。',
    'settings.optionalAssets.officeNotInstalled': '状态：未安装。办公文档工具保持禁用。',
    'settings.optionalAssets.headingPdf': 'PDF 解析器',
    'settings.optionalAssets.sectionPdfInfo': 'pdfjs-dist 库自带其 worker（约 1.6 MB）。摄入时从 PDF 附件提取文本所需。没有它，PDF 会被跳过。',
    'settings.optionalAssets.pdfNotInstalled': '状态：未安装。摄入时会跳过 PDF 文件。',
    'settings.optionalAssets.headingSelfDev': '自开发源码',
    'settings.optionalAssets.sectionSelfDevInfo': '插件自身源码的快照（约 5 MB），自修改工具（manage_source）可读取和编辑。因体积原因放在单独的 release tag；推荐通过本地文件安装。',
    'settings.optionalAssets.selfDevNotInstalled': '状态：未安装。manage_source 工具保持禁用。',
    'settings.tab.optionalAssets': '可选资源',

    // =========================================================================
    // Settings — Backup Tab
    // =========================================================================
    'settings.backup.introTitle': '备份',
    'settings.backup.introDesc': '把所有内容（设置、记忆、历史、技能、工作流）导出为一个文件。导入以恢复或迁移到新设备。',
    'settings.backup.desc': '导出和导入插件数据，用于备份或迁移到另一台设备。',
    'settings.backup.headingExport': '导出',
    'settings.backup.headingImport': '导入',
    'settings.backup.catSettings': '插件设置',
    'settings.backup.catSettingsDesc': 'API 密钥、模式、权限、所有配置',
    'settings.backup.catMemory': '智能体记忆',
    'settings.backup.catMemoryDesc': '长期记忆和会话摘要',
    'settings.backup.catHistory': '聊天历史',
    'settings.backup.catHistoryDesc': '完整对话记录',
    'settings.backup.catWorkflows': '工作流',
    'settings.backup.catWorkflowsDesc': '自定义工作流定义',
    'settings.backup.catRules': '自定义规则',
    'settings.backup.catRulesDesc': '自定义智能体规则',
    'settings.backup.catSkills': '自定义技能',
    'settings.backup.catSkillsDesc': '自定义技能定义',
    'settings.backup.catPluginSkills': '插件技能文件',
    'settings.backup.catPluginSkillsDesc': '由 `VaultDNA` 扫描器自动生成的技能和 readme 文件',
    'settings.backup.catVaultDNA': '`VaultDNA` 扫描缓存',
    'settings.backup.catVaultDNADesc': '插件扫描结果（vault-dna.json），导入时免重新扫描',
    'settings.backup.catSemanticIndex': '语义索引',
    'settings.backup.catSemanticIndexDesc': '知识数据库和向量索引（可通过重新索引重建）',
    'settings.backup.catLogs': '操作日志',
    'settings.backup.catLogsDesc': '智能体操作日志历史',
    'settings.backup.export': '导出备份',
    'settings.backup.exporting': '导出中…',
    'settings.backup.selectFile': '选择备份文件',
    'settings.backup.confirmImport': '确认导入',
    'settings.backup.importing': '导入中…',
    'settings.backup.cancel': '取消',
    'settings.backup.overwriteWarning': '现有文件将被覆盖。',
    'settings.backup.backupFrom': '备份于 {{date}}（v{{version}}）',
    'settings.backup.invalidFile': '无效的备份文件。格式无法识别。',
    'settings.backup.exported': '备份已导出：{{files}} 个文件，分属 {{categories}} 个类别（{{size}}）',
    'settings.backup.exportFailed': '导出失败：{{error}}',
    'settings.backup.imported': '备份已导入：{{files}} 个文件，分属 {{categories}} 个类别。重新加载 Obsidian 以完全生效。',
    'settings.backup.importFailed': '导入失败：{{error}}',

    // =========================================================================
    // Settings — Vault Tab
    // =========================================================================
    'settings.vault.desc': '检查点在智能体首次修改每个文件前对其做快照。任务结束后可一键撤销所有更改。',
    'settings.vault.headingCheckpoints': '检查点',
    'settings.vault.sectionCheckpointsInfo': '智能体首次写入某文件前，Vault Operator 会对其原始内容做快照。多步任务后，可从聊天中的撤销按钮回滚整次编辑。快照存放在智能体文件夹中；可按需或任务结束后自动清除。',
    'settings.vault.enableCheckpoints': '启用检查点',
    'settings.vault.enableCheckpointsDesc': '在智能体更改每个文件前保存其备份副本。任务后可用撤销按钮恢复原始内容。',
    'settings.vault.snapshotTimeout': '快照超时（秒）',
    'settings.vault.snapshotTimeoutDesc': '等待文件备份完成多久后跳过。文件很大时可调大。默认：30。',
    'settings.vault.autoCleanup': '任务后自动清理',
    'settings.vault.autoCleanupDesc': '任务结束后删除备份副本。节省磁盘空间。若想在任务后手动审阅备份则禁用。',

    // =========================================================================
    // Settings — Vault Tab: Task Extraction
    // =========================================================================
    'settings.vault.taskExtraction': '任务提取',
    'settings.vault.sectionTaskExtractionInfo': '当智能体的回复包含任务复选框（`- [ ] 做某事`）时，Vault Operator 可把这些任务拉出来，创建带 frontmatter（状态、来源聊天、如提及则含截止日期）的独立任务笔记。适用于“从这份会议记录里提取待办”等工作流。',
    'settings.vault.taskExtractionDesc': '检测智能体回复中的任务（- [ ] 项）并创建带结构化 frontmatter 的任务笔记。',
    'settings.vault.taskExtractionEnable': '启用任务提取',
    'settings.vault.taskExtractionEnableDesc': '每次智能体回复后扫描任务并显示选择模态框。',
    'settings.vault.taskFolder': '任务文件夹',
    'settings.vault.taskFolderDesc': '创建任务笔记和任务数据库的知识库文件夹。',
    'settings.vault.preferTaskNotes': '优先使用 `TaskNotes` 插件',
    'settings.vault.preferTaskNotesDesc': '当社区插件 `TaskNotes` 处于活动状态时，以其格式创建任务。否则使用内置格式。',
    'settings.vault.agentFolderHeading': '智能体文件夹',
    'settings.vault.sectionAgentFolderInfo': 'Vault Operator 在知识库内存放自身数据的位置：插件技能、知识库 DNA 快照、外放的临时结果、知识和记忆数据库。若希望插件文件放在特定位置（例如排除出 Obsidian Sync）则更改此项。更改路径时现有文件不会自动迁移；使用下方“迁移数据”按钮。',
    'settings.vault.agentFolderDesc': '插件存放自身文件的、相对于知识库的文件夹：插件技能、知识库 DNA 快照、外放的临时结果和本地知识数据库。更改此路径时现有文件不会自动迁移。',
    'settings.vault.agentFolder': '文件夹',
    'settings.vault.agentFolderFieldDesc': '默认为知识库内的隐藏文件夹。用选择器打开系统文件夹对话框，或输入路径。此版本部分支持知识库外的文件夹——插件技能、临时结果和本地知识数据库仍位于知识库内。',
    'settings.vault.agentFolderPick': '选择文件夹…',
    'settings.vault.agentFolderMigrate': '迁移数据',
    'settings.vault.agentFolderMigrateDesc': '把插件技能、知识库 DNA 快照和知识/记忆数据库从旧的智能体文件夹复制到当前文件夹。原件保留原位。确认新位置可用后手动删除它们。迁移后重新加载 Obsidian 以便数据库在新路径打开。',
    'settings.vault.agentFolderMigrateButton': '从旧文件夹迁移数据…',
    'settings.vault.headingIngest': '知识库摄入',
    'settings.vault.sectionIngestInfo': '在知识库之上构建类 wiki 层：每条笔记的摘要、可选的 frontmatter 镜像，以及基于 frontmatter 属性的收件箱笔记自动分诊。一切默认关闭。自动触发更改需重载插件才能生效。',

    // =========================================================================
    // Settings — Visual Intelligence Tab
    // =========================================================================
    'settings.visual.libreOffice': '`LibreOffice`',
    'settings.visual.libreOfficeNotFound': '未找到 `LibreOffice`',
    'settings.visual.libreOfficeFound': '已找到 `LibreOffice`：{{path}}',
    'settings.visual.downloadLibreOffice': '下载 `LibreOffice`',
    'settings.visual.customLibreOfficePath': '自定义 `LibreOffice` 路径',

    // =========================================================================
    // UI — Task Selection Modal
    // =========================================================================
    'ui.taskSelection.title': '检测到 {{count}} 个任务',
    'ui.taskSelection.subtitle': '哪些任务应创建为任务笔记？',
    'ui.taskSelection.hintTaskNotes': '任务将以 `TaskNotes` 格式创建。',
    'ui.taskSelection.hintDefault': '提示：社区插件 `TaskNotes` 提供扩展的任务管理。',
    'ui.taskSelection.selectNone': '全不选',
    'ui.taskSelection.selectAll': '全选',
    'ui.taskSelection.create': '创建 {{count}} 个',
    'ui.taskSelection.cancel': '取消',
    'ui.taskSelection.due': '截止：{{date}}',

    // =========================================================================
    // Notices — Task Extraction
    // =========================================================================
    'notice.taskNotesCreated': '已创建 {{count}} 条任务笔记{{format}}',
    'notice.taskNotesCreatedFormatSuffix': '（`TaskNotes` 格式）',
    'notice.taskNotesError': '创建任务笔记出错',
    'notice.taskExtractionError': '任务提取错误：{{error}}',

    // =========================================================================
    // Settings — Language Tab
    // =========================================================================
    'settings.language.introTitle': '显示语言',
    'settings.language.introDesc': '选择插件界面语言。与智能体的交流可用任何语言，与此设置无关。',
    'settings.language.language': '语言',
    'settings.language.languageDesc': '选择插件界面的显示语言。未翻译的字符串回退到英语。',
    'settings.language.restartHint': '重启 Obsidian 以使所有更改生效。',

    // =========================================================================
    // Constants — Provider Labels
    // =========================================================================
    'provider.custom': '自定义',

    // =========================================================================
    // Constants — Tool Labels
    // =========================================================================
    'tool.read_file': '读取文件',
    'tool.read_file.desc': '读取知识库文件的内容',
    'tool.list_files': '列出文件',
    'tool.list_files.desc': '列出目录中的文件和文件夹',
    'tool.search_files': '搜索文件',
    'tool.search_files.desc': '按关键词或正则搜索文件内容',
    'tool.get_vault_stats': '知识库统计',
    'tool.get_vault_stats.desc': '获取概览统计（文件数、标签等）',
    'tool.get_frontmatter': 'Frontmatter',
    'tool.get_frontmatter.desc': '从笔记读取 YAML frontmatter',
    'tool.search_by_tag': '按标签搜索',
    'tool.search_by_tag.desc': '查找带特定标签的笔记',
    'tool.get_linked_notes': '链接笔记',
    'tool.get_linked_notes.desc': '查找链接到或被某笔记链接的笔记',
    'tool.get_daily_note': '每日笔记',
    'tool.get_daily_note.desc': '获取或创建今天的每日笔记',
    'tool.open_note': '打开笔记',
    'tool.open_note.desc': '在编辑器中打开笔记',
    'tool.semantic_search': '语义搜索',
    'tool.semantic_search.desc': '用向量索引按含义查找笔记',
    'tool.query_base': '查询数据库',
    'tool.query_base.desc': '查询 Obsidian bases 数据库',
    'tool.write_file': '写入文件',
    'tool.write_file.desc': '创建新文件或完全覆盖',
    'tool.edit_file': '编辑文件',
    'tool.edit_file.desc': '对文件做定向编辑',
    'tool.append_to_file': '追加到文件',
    'tool.append_to_file.desc': '在文件末尾添加内容',
    'tool.create_folder': '创建文件夹',
    'tool.create_folder.desc': '在知识库中创建新文件夹',
    'tool.delete_file': '删除文件',
    'tool.delete_file.desc': '永久删除文件或文件夹',
    'tool.move_file': '移动 / 重命名',
    'tool.move_file.desc': '移动或重命名文件',
    'tool.list_checkpoints': '列出检查点',
    'tool.list_checkpoints.desc': '列出影子仓库中的自动预写快照',
    'tool.read_checkpoint': '读取检查点',
    'tool.read_checkpoint.desc': '读取某快照中的文件内容',
    'tool.diff_checkpoint': '比对检查点',
    'tool.diff_checkpoint.desc': '把快照与当前知识库状态对比',
    'tool.restore_checkpoint': '恢复检查点',
    'tool.restore_checkpoint.desc': '把文件（或整个任务）回滚到某快照',
    'tool.update_frontmatter': '更新 frontmatter',
    'tool.update_frontmatter.desc': '设置或更新 YAML frontmatter 字段',
    'tool.generate_canvas': '生成画布',
    'tool.generate_canvas.desc': '创建 Obsidian 画布文件',
    'tool.create_base': '创建数据库',
    'tool.create_base.desc': '创建 Obsidian bases 数据库',
    'tool.update_base': '更新数据库',
    'tool.update_base.desc': '修改 Obsidian bases 数据库',
    'tool.web_fetch': '抓取 URL',
    'tool.web_fetch.desc': '下载并读取网页',
    'tool.web_search': '网页搜索',
    'tool.web_search.desc': '搜索网络以获取当前信息',
    'tool.ask_followup_question': '询问用户',
    'tool.ask_followup_question.desc': '向用户提出澄清问题',
    'tool.attempt_completion': '完成任务',
    'tool.attempt_completion.desc': '表示任务已完成',
    'tool.update_todo_list': '更新待办',
    'tool.update_todo_list.desc': '在聊天中显示任务清单',
    'tool.new_task': '派生子智能体',
    'tool.new_task.desc': '把子任务委派给新智能体',
    'tool.use_mcp_tool': '协议工具',
    'tool.use_mcp_tool.desc': '通过协议服务器调用外部工具',

    // =========================================================================
    // Constants — Tool Group Labels
    // =========================================================================
    'toolGroup.read': '读取文件',
    'toolGroup.read.desc': '读取和搜索知识库文件',
    'toolGroup.vault': '知识库智能',
    'toolGroup.vault.desc': 'frontmatter、标签、反向链接、每日笔记、语义搜索、画布、数据库',
    'toolGroup.edit': '编辑文件',
    'toolGroup.edit.desc': '创建、编辑、移动和组织知识库文件与画布',
    'toolGroup.web': '网络访问',
    'toolGroup.web.desc': '抓取网页并搜索互联网',
    'toolGroup.agent': '智能体控制',
    'toolGroup.agent.desc': '任务规划、完成、澄清和子智能体派生',
    'toolGroup.mcp': '协议工具',
    'toolGroup.mcp.desc': '通过已配置的协议服务器调用外部工具',

    // =========================================================================
    // Chat UI — Sidebar
    // =========================================================================
    'ui.sidebar.title': 'Vault Operator',
    'ui.sidebar.settings': '设置',
    'ui.sidebar.vaultHealth': '有可用的知识库健康发现',
    'ui.sidebar.chatHistory': '聊天历史',
    'ui.sidebar.newChat': '新聊天',
    'ui.sidebar.selectMode': '选择模式',
    'ui.sidebar.selectModel': '选择模型',
    'ui.sidebar.selectTools': '选择工具',
    'ui.sidebar.selectMcpServers': '选择 MCP 服务器',
    'ui.sidebar.toggleWebSearch': '切换网页搜索',
    'ui.sidebar.attachFile': '附加文件',
    'ui.sidebar.addVaultFile': '添加知识库文件',
    'ui.sidebar.addContext': '添加上下文',
    'ui.sidebar.moreOptions': '更多选项',
    'ui.sidebar.webSearchOn': '网页搜索（开）',
    'ui.sidebar.webSearchOff': '网页搜索（关）',
    'ui.sidebar.saveToMemory': '把对话保存到记忆',
    'ui.history.saveToMemory': '把此对话保存到记忆',
    'ui.history.removeFromMemory': '从记忆中移除此对话',
    'ui.history.rename': '重命名对话',
    'ui.history.renameTitle': '重命名对话',
    'ui.history.renameMessage': '为此对话设置新标题。',
    'ui.history.renameSubmit': '重命名',
    'ui.history.filterMemoryOnly': '仅显示已保存到记忆的对话',
    'ui.suggestionBanner.hideAriaLabel': '隐藏连接建议（可在设置中重新启用）',
    'ui.suggestionBanner.hiddenNotice': '建议横幅已隐藏。在设置 → 嵌入向量 → 隐式连接下重新启用。',
    'ui.suggestionBanner.toggleCommand': '切换隐式连接横幅',
    'ui.sidebar.stop': '停止',
    'ui.sidebar.send': '发送消息',
    'ui.sidebar.placeholder': '在此输入消息…',
    'ui.sidebar.noModel': '无模型',
    'ui.sidebar.modeOverride': '{{label}}（模式覆盖）',
    'ui.sidebar.noModelsEnabled': '未启用模型，打开设置',
    'ui.sidebar.useGlobalDefault': '使用全局默认（{{label}}）',
    'ui.sidebar.globalDefault': '全局默认',
    'ui.sidebar.working': '处理中…',
    'ui.sidebar.reasoning': '推理中…',
    'ui.sidebar.reasoningCollapsed': '推理',
    'ui.sidebar.analyzing': '分析结果中…',
    'ui.sidebar.analyzingShort': '分析中…',
    'ui.sidebar.actionSingular': '1 个操作',
    'ui.sidebar.actionPlural': '{{count}} 个操作',
    'ui.sidebar.emptyResponse': '（智能体无回复）',
    'ui.sidebar.tokenUsage': '{{time}}  ·  输入 {{input}} · 输出 {{output}}',
    'ui.sidebar.contextCondensed': '上下文已压缩',
    'ui.sidebar.newConversation': '新对话',
    'ui.sidebar.conversation': '对话',
    'ui.sidebar.copy': '复制',
    'ui.sidebar.editResend': '编辑并重发',
    'ui.sidebar.currentFile': '当前',
    // FEAT-24-08 / ADR-114 Steering-Hook
    'ui.sidebar.steeringLabel': '引导',
    'ui.sidebar.steeringQueued': '已排队等待下一轮迭代',
    'ui.sidebar.steeringDelivered': '已在第 {{iteration}} 轮送达',
    'ui.sidebar.steeringDiscarded': '未送达（任务在排空前已结束）',
    'ui.sidebar.insertAtCursor': '在光标处插入',
    'ui.sidebar.createNote': '从回复创建笔记',
    'ui.sidebar.synthesisZettel': '创建综合笔记',
    'ui.sidebar.copyResponse': '复制回复',
    'ui.sidebar.regenerate': '重新生成回复',
    'ui.sidebar.deleteResponse': '删除回复',
    'ui.sidebar.sources': '{{count}} 个来源',
    'ui.sidebar.plan': '计划',
    'ui.sidebar.activity': '活动',
    'ui.sidebar.activityCount': '{{count}} 个操作',

    // =========================================================================
    // Chat UI — Options Menu
    // =========================================================================
    'ui.menu.refreshIndex': '刷新索引（当前文件）',
    'ui.menu.forceReindex': '强制重建知识库索引',
    'ui.menu.cancelIndexing': '取消索引',
    'ui.menu.addOpenNote': '把打开的笔记加入上下文',
    'ui.menu.autoAcceptEdits': '自动接受编辑',

    // =========================================================================
    // Chat UI — Tool Activity Labels
    // =========================================================================
    'ui.toolActivity.readFile': '读取文件',
    'ui.toolActivity.readFiles': '读取多个文件',
    'ui.toolActivity.listFiles': '列出文件',
    'ui.toolActivity.searching': '搜索中',
    'ui.toolActivity.readingMetadata': '读取元数据',
    'ui.toolActivity.findingLinks': '查找链接',
    'ui.toolActivity.searchingByTag': '按标签搜索',
    'ui.toolActivity.vaultOverview': '知识库概览',
    'ui.toolActivity.readingDailyNote': '读取每日笔记',
    'ui.toolActivity.readingDailyNotes': '读取多个每日笔记',
    'ui.toolActivity.fetchingPage': '抓取页面',
    'ui.toolActivity.fetchingPages': '抓取多个页面',
    'ui.toolActivity.searchingWeb': '搜索网络',
    'ui.toolActivity.semanticSearch': '语义搜索',
    'ui.toolActivity.semanticSearches': '多次语义搜索',

    // =========================================================================
    // Chat UI — Question Card
    // =========================================================================
    'ui.question.confirm': '确认选择',
    'ui.question.placeholder': '输入你的回答…',
    'ui.question.answer': '回答',

    // =========================================================================
    // Chat UI — Approval Card
    // =========================================================================
    'ui.approval.noteEdits': '笔记编辑',
    'ui.approval.vaultChanges': '知识库变更',
    'ui.approval.web': '网络',
    'ui.approval.mcp': 'MCP',
    'ui.approval.read': '读取',
    'ui.approval.modeSwitching': '模式切换',
    'ui.approval.subAgents': '子智能体',
    'ui.approval.pluginSkills': '插件技能',
    'ui.approval.pluginApi': '插件 API',
    'ui.approval.recipes': '配方',
    'ui.approval.sandbox': '沙箱执行',
    'ui.approval.notEnabled': '批准 {{group}}：{{tool}}',
    'ui.approval.allowOnce': '允许一次',
    'ui.approval.enableInSettings': '始终允许',
    'ui.approval.configDirWarning': '写入受保护目录：{{path}}。此目录中的文件控制插件、主题和 Obsidian 设置。意外更改可能改变 Obsidian 行为或以插件形式安装恶意代码。',
    'ui.approval.explain.writeFile': '智能体想要创建一个新文件：',
    'ui.approval.explain.editFile': '智能体想要编辑一个现有文件：',
    'ui.approval.explain.appendFile': '智能体想要向文件追加文本：',
    'ui.approval.explain.deleteFile': '智能体想要把文件移到回收站：',
    'ui.approval.explain.moveFile': '智能体想要移动一个文件：',
    'ui.approval.explain.moveFileTo': '到',
    'ui.approval.explain.createFolder': '智能体想要创建一个新文件夹：',
    'ui.approval.explain.sandbox': '智能体想要运行脚本以处理你知识库中的数据。',
    'ui.approval.explain.webFetch': '智能体想要抓取一个网页：',
    'ui.approval.explain.webSearch': '智能体想要搜索互联网：',
    'ui.approval.explain.newTask': '智能体想要为某子任务启动一个子智能体。',
    'ui.approval.explain.mcpTool': '智能体想要使用一个外部工具：',
    'ui.approval.explain.pluginApi': '智能体想要访问一个插件：',
    'ui.approval.explain.command': '智能体想要运行一个 Obsidian 命令：',
    'ui.approval.explain.recipe': '智能体想要运行一个配方：',
    'ui.approval.explain.switchMode': '智能体想要切换到另一个模式。',
    'ui.approval.explain.frontmatter': '智能体想要更改一条笔记的元数据：',
    'ui.approval.explain.canvas': '智能体想要创建一个画布可视化：',
    'ui.approval.explain.excalidraw': '智能体想要创建一个 Excalidraw 绘图：',
    'ui.approval.explain.selfModify': '智能体想要更改其自身配置。',
    'ui.approval.explain.fallback': '智能体想要执行以下操作：',
    'ui.approval.explain.showDetails': '显示详情',
    'ui.approval.explain.hideDetails': '隐藏详情',

    // =========================================================================
    // Chat UI — Checkpoint
    // =========================================================================
    'ui.checkpoint.label': '检查点 · {{files}} · {{time}}',
    'ui.checkpoint.restore': '恢复检查点',
    'ui.checkpoint.undoThis': '撤销此更改',
    'ui.checkpoint.undoFromHere': '从此处撤销所有更改',
    'ui.checkpoint.action.diff': '查看更改',
    'ui.checkpoint.action.more': '更多选项',
    'ui.checkpoint.keepChat': '保留聊天',
    'ui.checkpoint.deleteFromHere': '从此处删除聊天',
    'ui.checkpoint.cancel': '取消',
    'ui.checkpoint.restoring': '恢复中…',
    'ui.checkpoint.error': '错误',
    'ui.checkpoint.nothingToRestore': '无可恢复内容',
    'ui.checkpoint.restored': '已恢复 {{count}} 个文件',
    'ui.checkpoint.failed': '失败',

    // =========================================================================
    // Chat UI — Undo Bar
    // =========================================================================
    'ui.undo.modified': '智能体修改了 {{count}} 个文件。',
    'ui.undo.undoAll': '撤销所有更改',
    'ui.undo.restoring': '恢复中…',
    'ui.undo.restored': '已恢复 {{count}} 个文件。',
    'ui.undo.noCheckpoint': '未找到可恢复的检查点。',
    'ui.undo.restoreFailed': '恢复失败。请查看控制台。',

    // =========================================================================
    // Chat UI — Error Messages
    // =========================================================================
    'ui.error.invalidKey': 'API 密钥无效。请检查智能体设置。',
    'ui.error.modelNotFound': '找不到模型。请在智能体设置中核对模型 ID。',
    'ui.error.rateLimit': '已达速率限制。请稍候。',
    'ui.error.overloaded': 'API 过载。请稍后重试。',
    'ui.error.network': '网络错误。检查你的连接以及本地服务器是否在运行。',
    'ui.error.generic': '错误',
    'ui.error.ollamaNotRunning': '{{model}} 无法启动。确保 Ollama 正在运行（`ollama serve`）且模型名正确。打开设置 → Vault Operator → 配置以验证。',

    // =========================================================================
    // Notices
    // =========================================================================
    'notice.webSearchEnabled': '网页搜索已启用。在设置 → 网页搜索中设置搜索提供商。',
    'notice.memoryDisabled': '记忆已禁用。在设置中启用后再试。',
    'notice.memoryNoActiveConversation': '没有可保存的活动对话。',
    'notice.memorySaveQueued': '对话已排队等待记忆提取。',
    'notice.memorySaveFailed': '保存对话失败。详情见控制台。',
    'notice.memoryRemoved': '已从“{{title}}”的记忆中移除 {{count}} 条事实。',
    'notice.modeSwitched': '已切换到 {{mode}} 模式',
    'notice.taskComplete': '智能体任务完成',
    'notice.loadConversationFailed': '无法加载对话',
    'notice.conversationNotFound': '此对话已不存在。它可能已从历史中删除。',
    'notice.copied': '已复制。',
    'notice.insertedAtCursor': '已在光标处插入。',
    'notice.noOpenNote': '未找到打开的笔记。请先在编辑器中打开一条笔记。',
    'notice.copiedToClipboard': '已复制到剪贴板',
    'notice.createNoteFailed': '无法创建笔记：{{error}}',
    'notice.zettelCreated': '已创建综合笔记',
    'notice.noActiveFile': '无活动文件',
    'notice.semanticDisabled': '语义索引已禁用',
    'notice.indexRefreshed': '已刷新当前文件的索引',
    'notice.indexingInProgress': '索引正在进行中',
    'notice.reindexingVault': '正在后台重建知识库索引…',
    'notice.vaultIndexRebuilt': '知识库索引已重建',
    'notice.reindexFailed': '重建失败：{{error}}',
    'notice.indexingCancelled': '索引已取消。部分进度已保存。',
    'notice.autoAcceptEdits': '自动接受编辑：{{value}}',

    // =========================================================================
    // ToolPicker Popover
    // =========================================================================
    'ui.toolPicker.title': '工具与技能',
    'ui.toolPicker.openFailed': '无法打开工具选择器。详情见开发者控制台。',
    'ui.mcpPicker.title': 'MCP 服务器',
    'ui.mcpPicker.empty': '未配置 MCP 服务器。在设置 → 服务提供商 → MCP 中添加一个。',
    'ui.mcpPicker.openFailed': '无法打开 MCP 选择器。详情见开发者控制台。',
    'ui.toolPicker.selected': '已选 {{count}} 个',
    'ui.toolPicker.filter': '筛选…',
    'ui.toolPicker.builtIn': '内置工具',
    'ui.toolPicker.mcpServers': '协议服务器',
    'ui.toolPicker.noMcpServers': '未配置协议服务器。',
    'ui.toolPicker.loading': '加载中…',
    'ui.toolPicker.workflows': '工作流',
    'ui.toolPicker.noWorkflows': '未找到工作流。',
    'ui.toolPicker.errorWorkflows': '加载工作流出错。',
    'ui.toolPicker.mcpServer': '协议服务器',

    // =========================================================================
    // VaultFilePicker
    // =========================================================================
    'ui.filePicker.search': '搜索知识库文件…',
    'ui.filePicker.add': '添加',
    'ui.filePicker.selected': '已选 {{count}} 个',
    'ui.filePicker.noFiles': '未找到文件',
    'ui.filePicker.activeFile': '活动：{{name}}',

    // =========================================================================
    // History Panel
    // =========================================================================
    'ui.history.title': '聊天历史',
    'ui.history.filter': '筛选…',
    'ui.history.empty': '暂无对话',
    'ui.history.today': '今天',
    'ui.history.yesterday': '昨天',
    'ui.history.thisWeek': '本周',
    'ui.history.older': '更早',
    'ui.history.messageCount': '{{count}} 条消息',
    'ui.history.copyLink': '复制聊天链接',
    'ui.history.linkCopied': '聊天链接已复制',
    'ui.history.addToNote': '把链接添加到活动笔记',
    'ui.history.linkAdded': '聊天链接已添加到笔记',
    'ui.history.linkAlreadyExists': '链接已存在于笔记中',
    'ui.history.linkAddFailed': '添加链接失败',
    'ui.history.noActiveNote': '无活动的 Markdown 笔记',

    // =========================================================================
    // Attachment Handler
    // =========================================================================
    'ui.attachment.tooLarge': '“{{name}}”超过 50 MB 限制。',
    'ui.attachment.unsupported': '不支持“{{name}}”。请使用图片、办公文档（PPTX/XLSX/DOCX/PDF）或文本文件。',
    'ui.attachment.readFailed': '无法读取“{{path}}”',
    'ui.attachment.largeDocument': '“{{name}}”非常大。对话中内容可能被压缩。',

    // =========================================================================
    // Modal — New Mode
    // =========================================================================
    'modal.newMode.title': '新智能体',
    'modal.newMode.name': '名称',
    'modal.newMode.nameDesc': '显示名（如 “daily planner”）',
    'modal.newMode.shortDesc': '简短描述（给人看）',
    'modal.newMode.shortDescHint': '在智能体选择下拉中显示的简短描述。',
    'modal.newMode.shortDescPlaceholder': '简短描述…',
    'modal.newMode.roleDefinition': '角色定义',
    'modal.newMode.roleDefinitionHint': '定义智能体的专长和人格。',
    'modal.newMode.roleDefinitionPlaceholder': '描述智能体的身份、行为和专注领域…',
    'modal.newMode.customInstructions': '模式专属自定义指令（可选）',
    'modal.newMode.customInstructionsHint': '此模式的附加行为准则。',
    'modal.newMode.customInstructionsPlaceholder': '附加准则…',
    'modal.newMode.saveLocation': '保存位置',
    'modal.newMode.saveLocationHint': '全局模式在你所有 Obsidian 知识库中可用。',
    'modal.newMode.thisVault': '此知识库',
    'modal.newMode.thisVaultHint': '仅此知识库',
    'modal.newMode.global': '全局',
    'modal.newMode.globalHint': '此机器上的所有知识库',
    'modal.newMode.create': '创建模式',
    'modal.newMode.cancel': '取消',
    'modal.newMode.nameRequired': '名称为必填',
    'modal.newMode.roleRequired': '角色定义为必填',

    // =========================================================================
    // Modal — Model Config
    // =========================================================================
    'modal.modelConfig.addModel': '添加模型',
    'modal.modelConfig.addEmbedding': '添加嵌入模型',
    'modal.modelConfig.configure': '配置：{{name}}',
    'modal.modelConfig.provider': '提供商',
    'modal.modelConfig.quickPick': '快速选择',
    'modal.modelConfig.quickPickDesc': '选择以预填模型 ID',
    'modal.modelConfig.pickModel': '选择一个模型…',
    'modal.modelConfig.fetchModels': '从提供商 API 获取当前模型',
    'modal.modelConfig.modelsFetched': '已获取 {{count}} 个模型',
    'modal.modelConfig.fetchFailed': '获取模型失败：{{error}}。你仍可在下方字段手动输入模型 ID。',
    'modal.modelConfig.modelId': '模型 ID',
    'modal.modelConfig.modelIdDesc': 'API 调用中使用的精确 ID',
    'modal.modelConfig.modelIdPlaceholder': '`GPT-4o`',
    'modal.modelConfig.displayName': '显示名',
    'modal.modelConfig.displayNameDesc': '聊天工具栏中的标签',
    'modal.modelConfig.displayNamePlaceholder': '如 我的 {{name}}',
    'modal.modelConfig.apiKey': 'API 密钥',
    'modal.modelConfig.apiKeyPlaceholder': 'Sk-...',
    'modal.modelConfig.baseUrl': 'Base URL',
    'modal.modelConfig.apiVersion': 'API 版本',
    'modal.modelConfig.apiVersionDesc': '云部署所需（如 2024-10-21）',
    'modal.modelConfig.apiVersionPlaceholder': '2024-10-21',
    'modal.modelConfig.maxTokens': '最大输出 token',
    'modal.modelConfig.maxTokensDesc': '每次回复生成的 token 上限（回答加工具调用；启用扩展思考时推理预算另加）',
    'modal.modelConfig.maxTokensAuto': '自动（推荐）— 按模型设定，提示词较大时自动下调',
    'modal.modelConfig.maxTokensNote': '手动覆盖。这是上限而非成本杠杆——你按实际生成的 token 计费，而非按上限。仅在限制延迟时设低；过低会截断长回答和工具调用并触发重试循环。滑块上限为该模型的真实输出上限。',
    'modal.modelConfig.maxTokensUseRecommended': '使用推荐值（{{value}}）',
    'modal.modelConfig.maxTokensUseRecommendedTitle': '使用此模型的推荐最大输出 token',
    'modal.modelConfig.maxTokensPlaceholder': '32000',
    'modal.modelConfig.temperature': '温度',
    'modal.modelConfig.temperatureDesc': '回复的随机性（0 = 确定性，更高 = 更有创意）',
    'modal.modelConfig.customTemperature': '自定义温度',
    'modal.modelConfig.temperatureFixed': '此模型只接受 temperature = 1.0（由 API 强制）。',
    'modal.modelConfig.promptCaching': '提示词缓存',
    'modal.modelConfig.promptCachingDesc': '缓存系统提示词和近期消息以降低 API 成本（仅支持的提供商）',
    'modal.modelConfig.promptCachingTooltip': '提示词缓存降低重复请求的输入成本。Anthropic 首次缓存写入 +25%，其后每次缓存读取 -90%。2 次迭代后即净赚。典型智能体会话建议开启。',
    'modal.modelConfig.thinking': '扩展思考',
    'modal.modelConfig.thinkingDesc': '让模型在回答前先推理。在困难任务上提升质量（仅支持的模型）',
    'modal.modelConfig.thinkingNote': '启用时，温度由 API 强制为 1。',
    'modal.modelConfig.thinkingBudget': '思考预算',
    'modal.modelConfig.thinkingBudgetDesc': '内部推理的最大 token（1,024 - 128,000）',
    'modal.modelConfig.temperatureThinkingNote': '因启用了扩展思考，温度已锁定为 1.0。',
    'modal.modelConfig.testConnection': '测试连接',
    'modal.modelConfig.testing': '测试中…',
    'modal.modelConfig.add': '添加',
    'modal.modelConfig.save': '保存',
    'modal.modelConfig.cancel': '取消',
    'modal.modelConfig.modelIdRequired': '模型 ID 为必填',
    'modal.modelConfig.enterModelIdFirst': '请先输入模型 ID',
    'modal.modelConfig.browseInstalled': '浏览已安装模型',
    'modal.modelConfig.browseAvailable': '浏览可用模型',
    'modal.modelConfig.loadingModels': '加载中…',
    'modal.modelConfig.noModelsOllama': '未找到模型。请先拉取一个，如：ollama pull llama3.2',
    'modal.modelConfig.noModelsUrl': '在此 base URL 未找到模型。若该端点未实现 /v1/models，直接在上方字段输入模型 ID 并保存即可。',
    'modal.modelConfig.ollamaUnreachable': '无法连接本地服务器。确保它在运行后再试。',
    'modal.modelConfig.serverUnreachable': '无法连接服务器：{{error}}。检查 base URL。若该端点未实现 /v1/models，在上方手动输入模型 ID 并保存。',
    // Provider API key hints
    'modal.modelConfig.keyHint.anthropic': '以 sk-ant-... 开头',
    'modal.modelConfig.keyHint.openai': '以 sk-... 开头',
    'modal.modelConfig.keyHint.gemini': '来自 aistudio.google.com',
    'modal.modelConfig.keyHint.openrouter': '以 sk-or-... 开头',
    'modal.modelConfig.keyHint.azure': '你的云部署 API 密钥',
    'modal.modelConfig.keyHint.local': '本地服务留空',
    // Provider Base URL hints
    'modal.modelConfig.urlHint.ollama': '默认：`http://localhost:11434`',
    'modal.modelConfig.urlHint.lmstudio': '默认：`http://localhost:1234`（无需 /v1）',
    'modal.modelConfig.urlHint.azure': '你的端点直到 /openai，如 https://your-resource.openai.azure.com/openai',
    'modal.modelConfig.urlHint.custom': '包含 /v1 后缀，如 http://localhost:1234/v1',

    // =========================================================================
    // Modal — Code Import
    // =========================================================================
    'modal.codeImport.title': '从代码导入模型',
    'modal.codeImport.tag': '实验性',
    'modal.codeImport.instructions': '粘贴一段 Python、JavaScript 或 `cURL` 的 API 代码片段，自动提取模型配置。',
    'modal.codeImport.parse': '解析片段',
    'modal.codeImport.apiKey': 'API 密钥',
    'modal.codeImport.apiKeyDesc': '可选。也可稍后在每个模型的设置中添加。',
    'modal.codeImport.apiKeyPlaceholder': 'Sk-...',
    'modal.codeImport.temperature': '温度',
    'modal.codeImport.temperatureDesc': '智能体行为的默认值。需要时按模型自动调整。',
    'modal.codeImport.temperatureFixed': '由 API 固定为 {{temperature}}。',
    'modal.codeImport.testConnection': '测试连接',
    'modal.codeImport.cancel': '取消',
    'modal.codeImport.import': '导入',
    'modal.codeImport.importCount': '导入 {{count}} 个模型',
    'modal.codeImport.selectProvider': '选择一个提供商',
    'modal.codeImport.noModels': '未找到模型',
    'modal.codeImport.testingConnection': '测试中…',
    'modal.codeImport.testFailed': '连接测试失败',
    'modal.codeImport.tempHint': '提示：此模型可能需要固定温度。试试在上方把温度设为 1.0。',
    'modal.codeImport.selectProviderDropdown': '选择提供商…',
    'modal.codeImport.baseUrl': 'Base URL',
    'modal.codeImport.apiVersion': 'API 版本',
    'modal.codeImport.modelsFound': '找到的模型（{{count}}）：',
    'modal.codeImport.duplicate': '（已存在）',
    'modal.codeImport.selectProviderNotice': '请选择一个提供商。',
    'modal.codeImport.noModelsNotice': '未找到模型。',

    // =========================================================================
    // Modal — System Prompt Preview
    // =========================================================================
    'modal.promptPreview.title': '系统提示词：{{mode}}',
    'modal.promptPreview.copy': '复制到剪贴板',
    'modal.promptPreview.copied': '已复制！',

    // =========================================================================
    // Modal — Chat History
    // =========================================================================
    'modal.chatHistory.title': '聊天历史',
    'modal.chatHistory.empty': '尚无已保存的对话。对话在每次任务后自动保存。',
    'modal.chatHistory.untitled': '未命名',
    'modal.chatHistory.open': '打开',
    'modal.chatHistory.delete': '删除',
    'modal.chatHistory.emptyAfterDelete': '尚无已保存的对话。',

    // =========================================================================
    // Modal — Diff Review
    // =========================================================================
    'modal.diffReview.titleCheckpoint': '检查点差异',
    'modal.diffReview.titleReview': '审阅更改（{{count}} 个文件）',
    'modal.diffReview.noChanges': '无更改',
    'modal.diffReview.unchangedLines': '… {{count}} 行未更改',
    'modal.diffReview.keep': '保留',
    'modal.diffReview.undo': '撤销',
    'modal.diffReview.edit': '编辑',
    'modal.diffReview.editLabel': '编辑该段内容：',
    'modal.diffReview.cancelEdit': '取消',
    'modal.diffReview.applyEdit': '应用编辑',
    'modal.diffReview.undoAll': '全部撤销',
    'modal.diffReview.applySelected': '应用所选',
    'modal.diffReview.keepAll': '全部保留',
    'modal.diffReview.close': '关闭',
    'modal.diffReview.restoreCheckpoint': '恢复到此检查点',
    'modal.diffReview.restoring': '恢复中…',
    'modal.diffReview.restored': '已恢复',
    'modal.diffReview.failed': '失败',

    // =========================================================================
    // Modal — Vault Health Repair
    // =========================================================================
    'modal.vaultHealth.title': '知识库健康检查',
    'modal.vaultHealth.checkOrphans': '孤立笔记（无入链）',
    'modal.vaultHealth.checkMissingBacklinks': '缺失的反向链接',
    'modal.vaultHealth.checkBrokenLinks': '断链',
    'modal.vaultHealth.checkWeakClusters': '语义相关但未链接的对',
    'modal.vaultHealth.checkInconsistentTags': '不一致的标签',
    'modal.vaultHealth.checkCategoryMismatch': '错误的分类指派',
    'modal.vaultHealth.checkGodNodes': '过载的枢纽笔记',
    'modal.vaultHealth.repairableCount': '{{count}} 项发现可自动修复（反向链接、分类、孤立边）。',
    'modal.vaultHealth.repairBtn': '修复',
    'modal.vaultHealth.repairing': '修复中…',
    'modal.vaultHealth.closeBtn': '关闭',
    'modal.vaultHealth.repairRunning': '修复进行中…',
    'modal.vaultHealth.creatingCheckpoint': '正在创建检查点…',
    'modal.vaultHealth.progressOrphanedEdges': '清理孤立边…',
    'modal.vaultHealth.progressBacklinks': '插入缺失的反向链接…',
    'modal.vaultHealth.progressCategories': '纠正分类指派…',
    'modal.vaultHealth.progressInvalidLinks': '清理无效链接…',
    'modal.vaultHealth.progressVerify': '验证结果…',
    'modal.vaultHealth.repairDone': '修复完成',
    'modal.vaultHealth.resultEdges': '已移除 {{count}} 条孤立边',
    'modal.vaultHealth.resultBacklinks': '{{entities}} 个实体：创建 {{links}} 条反向链接、{{bases}} 个数据库',
    'modal.vaultHealth.resultCategories': '{{count}} 条笔记：已纠正分类指派',
    'modal.vaultHealth.resultInvalidLinks': '已移除 {{count}} 条无效链接',
    'modal.vaultHealth.noRepairsNeeded': '无需修复。一切干净。',
    'modal.vaultHealth.remaining': '剩余：{{count}} 项发现（{{critical}} 项紧急）。',
    'modal.vaultHealth.undoBtn': '撤销',
    'modal.vaultHealth.doneBtn': '完成',
    'modal.vaultHealth.restoring': '正在恢复检查点…',
    'modal.vaultHealth.restored': '已恢复',
    'modal.vaultHealth.restoredCount': '已恢复 {{count}} 个文件。',
    'modal.vaultHealth.errors': '{{count}} 个错误：{{errors}}',
    'modal.vaultHealth.restoreFailed': '恢复失败',

    // =========================================================================
    // Main Plugin
    // =========================================================================
    'plugin.ribbonTooltip': 'Vault Operator',
    'plugin.commandOpen': '打开智能体侧栏',

    // =========================================================================
    // Onboarding (German UI — localized per language)
    // =========================================================================
    'onboarding.welcome.heading': '欢迎使用智能体',
    'onboarding.welcome.modelNeeded': '开始之前，智能体需要访问一个语言模型。',
    'onboarding.welcome.quickFree': '选一个提供商，粘贴 API 密钥，测试连接——一分钟内完成。',
    'onboarding.welcome.setupButton': '设置一个模型',
    'onboarding.welcome.freeButton': '免费试用',
    'onboarding.welcome.apiKeyButton': '我有 API 密钥',
    'onboarding.free.intro': '有一个前沿模型可免费使用。无需信用卡。',
    'onboarding.free.howTo': '如何获取你的 API 密钥：',
    'onboarding.free.step1': '1. 打开 [Google AI Studio API 密钥页面](https://aistudio.google.com/app/apikey)',
    'onboarding.free.step2': '2. 用你的账号登录并接受服务条款',
    'onboarding.free.step3': '3. 点击“create API key”',
    'onboarding.free.step4': '4. 选择一个现有项目或新建一个',
    'onboarding.free.step5': '5. 复制密钥',
    'onboarding.free.noCreditCard': '无需信用卡。[定价](https://ai.google.dev/gemini-api/docs/pricing) | [速率限制](https://ai.google.dev/gemini-api/docs/rate-limits)',
    'onboarding.free.pasteKey': '把密钥粘贴到这里的聊天中。',
    'onboarding.provider.selectPrompt': '你想使用哪个提供商？',
    'onboarding.provider.anthropic': 'Anthropic',
    'onboarding.provider.google': 'Google',
    'onboarding.provider.pasteKey': '{{label}}：把你的 API 密钥粘贴到这里的聊天中。',
    'onboarding.noModel.heading': '未配置模型。要开始，请设置一个带 API 密钥的提供商。',
    'onboarding.noModel.setupHint': '打开模型设置表单，选择提供商、粘贴 API 密钥并测试连接。Google 提供无需信用卡的免费额度。',
    'onboarding.noModel.settingsButton': '打开设置',
    'onboarding.test.testing': '测试连接中…',
    'onboarding.test.success': '连接成功！{{provider}} 已配置。',
    'onboarding.test.failed': '无法验证密钥。请检查密钥后重试。',
    'onboarding.trigger': '开始设置',

    // =========================================================================
    // Provider Setup Guides (in ModelConfigModal)
    // =========================================================================
    'guide.anthropic.heading': '如何获取你的 API 密钥：',
    'guide.anthropic.step1': '前往 console.anthropic.com 并登录（或创建账号）。',
    'guide.anthropic.step2': '点击左侧边栏的“API keys”。',
    'guide.anthropic.step3': '点击“create key”，命名并复制它。',
    'guide.anthropic.step4': '把密钥（以 sk-ant-... 开头）粘贴到上方的 API 密钥字段。',
    'guide.anthropic.tip': '推荐模型：claude-sonnet-4-6-20250514（速度与质量的良好平衡）。',
    'guide.openai.heading': '如何获取你的 API 密钥：',
    'guide.openai.step1': '前往 platform.openai.com 并登录。',
    'guide.openai.step2': '点击你的名字（右上角）→ “API keys”。',
    'guide.openai.step3': '点击“create new secret key”并立即复制（之后无法再看到）。',
    'guide.openai.step4': '把密钥（以 sk-... 开头）粘贴到上方的 API 密钥字段。',
    'guide.openai.tip': '推荐模型：gpt-4o。经济替代：gpt-4o-mini。',
    'guide.gemini.heading': '如何获取你的 API 密钥：',
    'guide.gemini.step1': '前往 aistudio.google.com 并用你的账号登录。',
    'guide.gemini.step2': '点击“get API key”并为你的项目创建一个密钥。',
    'guide.gemini.step3': '复制密钥并粘贴到上方的 API 密钥字段。',
    'guide.gemini.tip': '推荐模型：gemini-2.5-flash（快速，有免费额度）。复杂任务：gemini-2.5-pro。',
    'guide.ollama.heading': '如何使用本地模型服务器（本地运行，零成本）：',
    'guide.ollama.step1': '从 ollama.ai 安装服务器。',
    'guide.ollama.step2': '打开终端并拉取一个模型，如：ollama pull llama3.2',
    'guide.ollama.step3': '服务器自动启动；base URL 默认为 `http://localhost:11434`。',
    'guide.ollama.step4': '把拉取到的模型名（如 llama3.2）原样填入上方的模型 ID 字段。',
    'guide.ollama.tip': '并非所有模型都支持工具调用。推荐：qwen2.5:7b、llama3.2、mistral。',
    'guide.openrouter.heading': '如何使用此提供商（一把钥匙访问 100+ 模型）：',
    'guide.openrouter.step1': '前往 openrouter.ai 创建一个免费账号。',
    'guide.openrouter.step2': '点击你的头像（右上角）→ keys → create key。',
    'guide.openrouter.step3': '复制密钥（以 sk-or-... 开头）并粘贴到上方的 API 密钥字段。',
    'guide.openrouter.step4': '输入模型 ID。使用精确的 OpenRouter 模型名，如 anthropic/claude-3.5-sonnet 或 openai/gpt-4o。',
    'guide.openrouter.step5': '在 openrouter.ai/models 浏览所有可用模型。',
    'guide.openrouter.tip': 'base URL 已预配置。许多模型有免费额度（在模型名中找 “:free”）。',
    'guide.azure.heading': '如何使用云部署（企业）：',
    'guide.azure.step1': '在云门户中，打开你的部署资源。',
    'guide.azure.step2': '在“资源管理”→“密钥和端点”下，复制密钥和端点 URL。',
    'guide.azure.step3': '在 base URL 中输入：{endpoint}/openai（如 https://my-resource.openai.azure.com/openai）。',
    'guide.azure.step4': '在模型 ID 中输入云控制台中的精确部署名（如 `GPT-4o`）。',
    'guide.azure.step5': '把 API 版本设为你的部署所支持的值（默认：2024-10-21）。',
    'guide.azure.tip': '企业网关：使用网关 base URL（直到 /openai）、部署名作为模型 ID 以及你的网关 API 密钥。',
    'guide.lmstudio.heading': '如何使用本地模型服务器（零成本、无 API 密钥）：',
    'guide.lmstudio.step1': '从 lmstudio.ai 下载应用并安装一个你选择的模型。',
    'guide.lmstudio.step2': '在应用中，进入 developer 标签页（左侧边栏）并启动本地服务器。',
    'guide.lmstudio.step3': '默认 base URL 为 `http://localhost:1234`，无需 API 密钥。',
    'guide.lmstudio.step4': '点击下方“浏览可用模型”选择一个已加载的模型。',
    'guide.lmstudio.tip': '启动服务器前务必在应用中加载一个模型，否则不会显示任何模型。',
    'guide.custom.heading': '自定义端点（任意兼容 API）：',
    'guide.custom.tip': '任意兼容端点。输入带 /v1 后缀的 base URL 和你的 API 密钥。',

    // GitHub Copilot
    'guide.copilot.heading': 'GitHub copilot（需有效订阅）：',
    'guide.copilot.step1': '你需要有效的 GitHub copilot 订阅（个人、商业或企业）。',
    'guide.copilot.step2': '点击下方“用 GitHub 登录”。会出现一个代码，在 github.com/login/device 输入它。',
    'guide.copilot.step3': '授权后，从快速选择下拉中挑选模型，或使用获取按钮。',
    'guide.copilot.disclaimer': '此为非官方 API。模型和可用性可能随时变更，恕不另行通知。',
    'copilot.auth': 'GitHub 账号',
    'copilot.authDesc': '用你的 GitHub 账号登录以使用 copilot 模型。',
    'copilot.signIn': '用 GitHub 登录',
    'copilot.signOut': '退出登录',
    'copilot.authenticated': '已连接',
    'copilot.notConnected': '未连接',
    'copilot.deviceCodeNotice': '在 GitHub 上输入此代码：',
    'copilot.polling': '等待授权中…',
    'copilot.authSuccess': '已成功连接到 GitHub copilot。',
    'copilot.authFailed': '认证失败：{error}',
    'copilot.signedOut': '已从 GitHub copilot 退出登录。',

    // ChatGPT OAuth (EPIC-021). The bot's sentence-case rule does not include
    // "ChatGPT" or "OS" in its default brand/acronym list, so the strings here
    // avoid those tokens. The i18n keys keep the chatgpt prefix for context.
    'chatgpt.auth': 'Codex 账号',
    'chatgpt.authDesc': '用你的订阅登录。此为非官方 codex 端点；schema 可能随时变更。',
    'chatgpt.signIn': '登录',
    'chatgpt.signOut': '断开',
    'chatgpt.notConnected': '未连接',
    'chatgpt.unsupportedPlatform': '仅限桌面端（需系统钥匙串）',
    'chatgpt.polling': '等待浏览器…',
    'chatgpt.openedBrowser': '浏览器已打开。在其中完成登录后返回 Obsidian。',
    'chatgpt.authSuccess': '已成功连接。',
    'chatgpt.authFailed': '登录失败：{error}',
    'chatgpt.signedOut': '已断开。',

    // Kilo gateway
    'kilo.auth': 'Kilo 账号',
    'kilo.authDesc': '用你的账号登录以使用网关模型。',
    'kilo.signIn': '登录',
    'kilo.manualToken': '使用 API token',
    'kilo.manualTokenPlaceholder': '粘贴你的 API token',
    'kilo.manualTokenConfirm': '连接',
    'kilo.manualTokenValidating': '验证中…',
    'kilo.manualTokenInvalid': '无效 token：{error}',
    'kilo.disconnect': '断开',
    'kilo.disconnected': '已从网关断开。',
    'kilo.authenticated': '已以 {account} 连接',
    'kilo.authenticatedNoLabel': '已连接',
    'kilo.notConnected': '未连接',
    'kilo.deviceFlow.openBrowser': '打开下方链接并输入代码：',
    'kilo.deviceFlow.code': '你的代码：{code}',
    'kilo.deviceFlow.waiting': '等待授权中…',
    'kilo.deviceFlow.success': '已成功连接到网关。',
    'kilo.deviceFlow.failed': '授权失败：{error}',

    // EPIC-26 / FEAT-26-03 -- Provider-only Settings UI
    'settings.providers.title': '服务提供商',
    'settings.providers.intro': '配置一个或多个 LLM 提供商；插件自动把它们的模型分为三档，活动提供商驱动聊天。',
    'settings.providers.empty': '尚未配置提供商。在下方添加一个。',
    'settings.providers.activeLabel': '活动提供商',
    'settings.providers.activeDesc': '此提供商驱动聊天；按情况切换，例如把隐私敏感的笔记放到本地模型上。',
    'settings.providers.activeNone': '— 无 —',
    'settings.providers.activeBadge': '活动',
    'settings.providers.notConfigured': '未配置',
    'settings.providers.rowSummary': '{{count}} 个模型 · {{flagship}} / {{mid}} / {{fast}}',
    'settings.providers.rowSummaryEmpty': '尚未刷新 · 点击齿轮进行配置',
    'settings.providers.rowSummaryDisabled': '已禁用 · 启用以使用',
    'settings.providers.configure': '配置',
    'settings.providers.headerProvider': '提供商',
    'settings.providers.headerKey': '密钥',
    'settings.providers.headerEnable': '启用',
    'settings.providers.headerDefault': '活动',
    'settings.providers.remove': '移除',
    'settings.providers.enabled': '已启用',
    'settings.providers.apiKey': 'API 密钥',
    'settings.providers.apiKeyDesc': '每次请求发送的凭据，加密存储在磁盘上。',
    'settings.providers.baseUrl': 'Base URL',
    'settings.providers.baseUrlDesc': '端点 URL。留空使用提供商默认；覆盖以指向代理、自托管网关或备用区域。',
    'settings.providers.baseUrlSdkDefault': 'SDK 默认',
    'settings.providers.apiVersion': 'API 版本',
    'settings.providers.apiVersionDesc': '企业网关的 api-version 字符串，如 2024-10-21。',
    'settings.providers.bedrockRegion': 'AWS 区域',
    'settings.providers.bedrockRegionDesc': 'AWS 区域标识符（如 eu-central-1 或 us-east-1）。',
    'settings.providers.bedrockAuthMode': '认证模式',
    'settings.providers.bedrockAuthModeDesc': 'API 密钥（单一 bearer token）或 access key + secret（经典 IAM）。',
    'settings.providers.bedrockApiKey': 'Bedrock API 密钥',
    'settings.providers.bedrockAccessKey': 'AWS access key ID',
    'settings.providers.bedrockSecretKey': 'AWS secret access key',
    'settings.providers.oauthSignIn': '登录',
    'settings.providers.oauthSignOut': '退出登录',
    'settings.providers.oauthReauth': '重新认证',
    'settings.providers.oauthStatus': '登录状态',
    'settings.providers.oauthAuthed': '已登录',
    'settings.providers.oauthNotAuthed': '未登录',
    'settings.providers.oauthSignInRedirect': '登录仍在旧版模型标签页中；正在打开。',
    'settings.providers.oauthRequestingCode': '正在请求代码…',
    'settings.providers.oauthPolling': '等待浏览器…',
    'settings.providers.oauthDeviceCode': 'GitHub Copilot 设备码：{{code}}\n打开 {{url}} 并输入该代码。',
    'settings.providers.oauthSignedIn': '登录成功。',
    'settings.providers.oauthSignedOut': '已退出登录。',
    'settings.providers.oauthSignInFailed': '登录失败：{{msg}}',
    'settings.providers.oauthSignOutFailed': '退出失败：{{msg}}',
    'settings.providers.chatgptUnsupported': 'ChatGPT 登录需要带 OS 钥匙串的桌面版 Obsidian。',
    'settings.providers.copilotClientId': '自定义 GitHub client ID',
    'settings.providers.copilotClientIdDesc': '可选。用你自己的 GitHub 应用覆盖默认 client。',
    'settings.providers.copilotClientIdPlaceholder': 'Iv1.b507a08c87ecfe98（默认）',
    'settings.providers.discovery': '已发现的模型',
    'settings.providers.discoveryDesc': '{{count}} 个模型 · 上次刷新：{{stamp}}',
    'settings.providers.discoveryEmpty': '尚未发现模型。添加凭据后刷新。',
    'settings.providers.discoveryCodex': '已知 Codex 阵容（{{count}}）。此后端无模型列表，较新的 id 可在档位槽中手动输入。',
    'settings.providers.discoveryCodexEmpty': '刷新后显示已知模型阵容。此后端无模型列表，较新的 id 可在档位槽中手动输入。',
    'settings.providers.refresh': '刷新',
    'settings.providers.refreshing': '刷新中…',
    'settings.providers.refreshDone': '模型已刷新。',
    'settings.providers.refreshFailed': '刷新失败：{{msg}}',
    'settings.providers.refreshUnavailable': '发现服务尚未就绪。稍后再试。',
    'settings.providers.advisorDisabled': '此提供商已禁用顾问模式——无前沿档模型。',
    'settings.providers.removeProvider': '移除提供商',
    'settings.providers.removeDesc': '删除此提供商的凭据和档位映射。原模型保留在 legacy_active_models_backup 中。',
    'settings.providers.removeConfirm': '移除提供商“{{name}}”？这将删除其凭据和档位映射。',
    'settings.providers.addProviderLabel': '添加提供商',
    'settings.providers.addProviderDesc': '选择要添加的提供商类型；允许同一类型的多个实例（例如同一提供商的两个账号）。',
    'settings.providers.addProvider': '添加提供商',
    'settings.providers.choosePicker': '— 选择提供商类型 —',
    'settings.providers.duplicateSuffix': '第二个实例',
    'settings.providers.tier.fast': '经济档',
    'settings.providers.tier.mid': '主档',
    'settings.providers.tier.flagship': '前沿档',
    'settings.providers.tier.fastDesc': '最便宜、延迟最低的模型；用于上下文压缩、命名和研究子智能体。',
    'settings.providers.tier.midDesc': '自动模式下默认的主循环模型；成本与能力均衡。',
    'settings.providers.tier.flagshipDesc': '最强大的模型；用于咨询前沿的一次性综合步骤。留空则禁用顾问模式。',
    'settings.providers.tier.autoLabel': '自动 → {{name}}',
    'settings.providers.tier.autoEmpty': '— 无自动匹配 —',
    'settings.providers.tier.autoDetected': '自动检测',
    'settings.providers.tier.manuallySet': '手动设置',
    'settings.providers.tier.empty': '未分配',
    'settings.providers.tier.differentTier': '不同档位',
    'settings.providers.tier.manualOption': '手动输入模型 ID…',
    'settings.providers.tier.manualPlaceholder': '示例：gpt-5.3-codex',
    'settings.providers.tier.manualBack': '使用列表',
    'settings.providers.modal.title': '配置 {{name}}',
    'settings.providers.modal.titleNew': '添加提供商',
    'settings.providers.modal.section.identity': '身份',
    'settings.providers.modal.section.auth': '认证',
    'settings.providers.modal.section.discovery': '发现',
    'settings.providers.modal.section.tiers': '档位映射',
    'settings.providers.modal.section.danger': '危险区',
    'settings.providers.modal.close': '关闭',
    'settings.providers.modal.cancel': '取消',
    'settings.providers.modal.save': '保存',
    'settings.providers.modal.addProvider': '添加提供商',
    'settings.providers.modal.addedNotice': '已添加 {{name}}。刷新模型列表以填充档位槽。',
    'settings.providers.modal.notFound': '找不到提供商。列表可能已变更；关闭后重新打开。',
    'settings.providers.modal.providerType': '提供商',
    'settings.providers.modal.displayName': '显示名',
    'settings.providers.modal.displayNameDesc': '在提供商列表中显示的友好标签。默认为提供商类型。',
    'settings.providers.modal.discoveryAfterSave': '先保存提供商，再刷新以发现其模型。',
    'settings.providers.modal.tiersAfterRefresh': '刷新以发现模型并自动填充档位槽。',
    'settings.providers.modal.refreshDirtyConfirm': '你有未保存的凭据更改；刷新使用已保存的凭据，仍要继续吗？',
    'settings.providers.modal.autoFetching': '正在为 {{name}} 发现模型…',
    'settings.providers.modal.autoFetched': '已为 {{name}} 发现 {{count}} 个模型。',
    'settings.providers.modal.autoFetchFailed': '自动发现失败：{{msg}}。使用刷新按钮重试。',
    'settings.providers.modal.tierInfoTitle': '档位映射',
    'settings.providers.modal.tierInfoBody': '每个提供商有三个档位槽；经济槽驱动廉价辅助调用，主槽驱动默认聊天循环，前沿槽驱动顾问升级；自动发现按模型模式填充，每个槽都可单独覆盖为指定模型。',
    'settings.providers.modal.testConnection': '测试连接',
    'settings.providers.modal.testConnectionDesc': '用当前凭据探测提供商端点以验证是否可用。',
    'settings.providers.modal.testing': '测试中…',
    'settings.providers.modal.testOk': '连接正常。{{msg}}',
    'settings.providers.modal.testFail': '连接失败：{{msg}}',
    'settings.providers.modal.testNoCreds': '请先输入凭据再测试。',

    // EPIC-26 / FEAT-26-05 -- chat-header model dropdown
    'ui.sidebar.modelAuto': '自动',
    'ui.sidebar.modelAutoTitle': '顾问模式：主循环跑在主档，按需升级到前沿档。',
    'ui.sidebar.modelOverrideTitle': '覆盖：本轮跑在 {{label}}。consult_flagship 已禁用。',
    'ui.sidebar.modelAdvisorDisabled': '顾问模式已禁用',
    'ui.sidebar.modelPickerTitle': '{{provider}} 模型',
    'ui.sidebar.modelPickerSearch': '筛选模型…',
    'ui.sidebar.modelPickerNoModels': '尚未发现模型；打开设置 → 服务提供商 → 刷新。',

    // Issue #44 -- per-conversation extended-thinking override
    'ui.sidebar.thinkingOverrideLabel': '思考',
    'ui.sidebar.thinkingOverrideFollow': '跟随模型',
    'ui.sidebar.thinkingOverrideOn': '开',
    'ui.sidebar.thinkingOverrideOff': '关',
    // Binary thinking switch state text
    'ui.sidebar.thinkingOn': '开',
    'ui.sidebar.thinkingOff': '关',
    'ui.sidebar.thinkingOverrideTitleOn': '{{label}} 此对话强制开启扩展思考。',
    'ui.sidebar.thinkingOverrideTitleOff': '{{label}} 此对话强制关闭扩展思考。',
    // Per-conversation reasoning-effort override (shown when thinking is on)
    'ui.sidebar.effortLabel': '推理力度',
    'ui.sidebar.effortAuto': '自动',
    'ui.sidebar.effortMinimal': '最小',
    'ui.sidebar.effortLow': '低',
    'ui.sidebar.effortMedium': '中',
    'ui.sidebar.effortHigh': '高',
    'ui.sidebar.effortXhigh': '超高',
    'ui.sidebar.effortMax': '最大',
    'ui.sidebar.effortAutoHint': '路由开启时力度自动设定。固定一个模型以手动控制。',
};
